# Generated by Django 3.0.5 on 2020-05-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='checks_failing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='checks_failing',
        ),
    ]
