# Generated by Django 3.0.7 on 2020-06-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_auto_20200609_1607"),
        ("clients", "0002_auto_20200531_2058"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="automation.Policy",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="automation.Policy",
            ),
        ),
    ]
