# Generated by Django 3.1.7 on 2021-03-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20210329_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomfield',
            name='checkbox_value',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='sitecustomfield',
            name='checkbox_value',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
