# Generated by Django 3.1.7 on 2021-04-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20210329_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='block_policy_inheritance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='block_policy_inheritance',
            field=models.BooleanField(default=False),
        ),
    ]
