# Generated by Django 4.0.5 on 2022-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0022_change_arch_to_goarch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deployment",
            old_name="arch",
            new_name="goarch",
        ),
        migrations.AlterField(
            model_name="deployment",
            name="goarch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("amd64", "amd64"),
                    ("386", "386"),
                    ("arm64", "arm64"),
                    ("arm", "arm"),
                ],
                default="amd64",
                max_length=255,
            ),
        ),
    ]
