# Generated by Django 4.0.5 on 2022-06-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_deployment_arch_deployment_goarch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='goarch',
            field=models.CharField(choices=[('amd64', 'amd64'), ('386', '386'), ('arm64', 'arm64'), ('arm', 'arm')], default='amd64', max_length=255),
        ),
    ]
