# Generated by Django 4.2.14 on 2024-07-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_deployment_goarch'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='trayicon',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
