# Generated by Django 3.1.1 on 2020-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0006_auto_20200923_1753"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="debug_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
