# Generated by Django 3.2.1 on 2021-07-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_alter_auditlog_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaction',
            name='cancelable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('schedreboot', 'Scheduled Reboot'), ('taskaction', 'Scheduled Task Action'), ('agentupdate', 'Agent Update'), ('chocoinstall', 'Chocolatey Software Install'), ('runcmd', 'Run Command'), ('runscript', 'Run Script'), ('runpatchscan', 'Run Patch Scan'), ('runpatchinstall', 'Run Patch Install')], max_length=255, null=True),
        ),
    ]
