# Generated by Django 3.2.6 on 2021-10-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_alter_auditlog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='agent_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
