# Generated by Django 3.2.6 on 2021-10-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0020_alter_auditlog_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='agent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
