# Generated by Django 3.2.12 on 2022-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0022_auto_20211105_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('schedreboot', 'Scheduled Reboot'), ('agentupdate', 'Agent Update'), ('chocoinstall', 'Chocolatey Software Install'), ('runcmd', 'Run Command'), ('runscript', 'Run Script'), ('runpatchscan', 'Run Patch Scan'), ('runpatchinstall', 'Run Patch Install')], max_length=255, null=True),
        ),
    ]
