FROM node:stretch

WORKDIR /home/node/app
ARG MESH_HOST
RUN apt-get update && apt-get install -y gettext-base
RUN npm install meshcentral
COPY config.json ./meshcentral-data/config.json.tmp
RUN envsubst '\$MESH_HOST' < /home/node/app/meshcentral-data/config.json.tmp > /home/node/app/meshcentral-data/config.json && \
    rm /home/node/app/meshcentral-data/config.json.tmp

CMD ["node", "./node_modules/meshcentral/meshcentral"]