# Generated by Django 3.0.4 on 2020-03-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_check_interval', models.PositiveIntegerField(default=300)),
                ('cpuload_check_interval', models.PositiveIntegerField(default=300)),
                ('mem_check_interval', models.PositiveIntegerField(default=300)),
            ],
        ),
    ]
