# Generated by Django 3.0.6 on 2020-05-16 07:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alert_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, default=list, null=True, size=None)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True)),
                ('smtp_host_user', models.EmailField(blank=True, default='admin@example.com', max_length=254, null=True)),
                ('smtp_host_password', models.CharField(blank=True, default='changeme', max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, default=587, null=True)),
            ],
        ),
    ]
