# Generated by Django 3.0.4 on 2020-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='win_svc_check_interval',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
