# Generated by Django 3.0.5 on 2020-05-02 23:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coresettings',
            name='cpuload_check_interval',
        ),
        migrations.RemoveField(
            model_name='coresettings',
            name='disk_check_interval',
        ),
        migrations.RemoveField(
            model_name='coresettings',
            name='mem_check_interval',
        ),
        migrations.RemoveField(
            model_name='coresettings',
            name='win_svc_check_interval',
        ),
        migrations.AddField(
            model_name='coresettings',
            name='email_alert_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
