# Generated by Django 3.0.5 on 2020-05-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200502_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='smtp_host_password',
            field=models.CharField(blank=True, default='changeme', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='smtp_host_user',
            field=models.EmailField(blank=True, default='admin@example.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
