# Generated by Django 3.0.8 on 2020-07-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200629_2033"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coresettings",
            name="smtp_use_tls",
        ),
        migrations.AddField(
            model_name="coresettings",
            name="smtp_from_email",
            field=models.CharField(
                blank=True, default="from@example.com", max_length=255, null=True
            ),
        ),
    ]
