# Generated by Django 3.1 on 2020-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20200812_0223"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="smtp_requires_auth",
            field=models.BooleanField(default=True),
        ),
    ]
