# Generated by Django 3.1.1 on 2020-09-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_auto_20200617_0332"),
        ("core", "0007_coresettings_smtp_requires_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="server_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_server_policy",
                to="automation.policy",
            ),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="workstation_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_workstation_policy",
                to="automation.policy",
            ),
        ),
    ]
