# Generated by Django 3.1.1 on 2020-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200910_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='initial_setup',
            field=models.BooleanField(default=True),
        ),
    ]
