# Generated by Django 3.1.1 on 2020-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20200910_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="agent_auto_update",
            field=models.BooleanField(default=True),
        ),
    ]
