# Generated by Django 3.1.1 on 2020-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_coresettings_agent_auto_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="modified_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="modified_time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
