# Generated by Django 3.1.4 on 2021-02-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20210207_1426'),
        ('core', '0012_coresettings_check_history_prune_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='alert_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_alert_template', to='alerts.alerttemplate'),
        ),
    ]
