# Generated by Django 3.1.7 on 2021-04-15 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_codesigntoken'),
        ('core', '0019_globalkvstore'),
    ]

    operations = [
    ]
