# Generated by Django 3.1.7 on 2021-05-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customfield_hide_in_ui'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern', models.TextField()),
            ],
        ),
    ]
