# Generated by hand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_coresettings_default_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="mesh_auto_login",
            field=models.BooleanField(default=True),
        ),
    ]
