# Generated by Django 4.0.3 on 2022-04-08 03:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_coresettings_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresettings',
            name='email_alert_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='sms_alert_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='smtp_from_email',
            field=models.CharField(blank=True, default='from@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='smtp_host_password',
            field=models.CharField(blank=True, default='changeme', max_length=255),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='smtp_host_user',
            field=models.CharField(blank=True, default='admin@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, default=587),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
