# Generated by Django 4.0.4 on 2022-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_coresettings_mesh_disable_auto_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
