# Generated by Django 4.2.6 on 2023-11-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_coresettings_open_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaction',
            name='action_type',
            field=models.CharField(choices=[('web', 'Web'), ('rest', 'Rest')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='urlaction',
            name='rest_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='urlaction',
            name='rest_headers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='urlaction',
            name='rest_method',
            field=models.CharField(choices=[('get', 'Get'), ('post', 'Post'), ('put', 'Put'), ('delete', 'Delete'), ('patch', 'Patch')], default='get', max_length=10),
        ),
    ]
