# Generated by Django 4.2.9 on 2024-01-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_coresettings_default_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="smtp_from_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
