# Generated by Django 4.2.7 on 2023-11-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_coresettings_default_time_zone'),
        ('core', '0038_urlaction_action_type_urlaction_rest_body_and_more'),
    ]

    operations = [
    ]
