# Generated by Django 4.2.10 on 2024-02-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20231122_0501'),
        ('core', '0041_auto_20240128_0301'),
    ]

    operations = [
    ]
