# Generated by Django 4.2.11 on 2024-04-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_coresettings_mesh_disable_auto_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='systray_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
