# Generated by Django 4.2.13 on 2024-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_coresettings_enable_server_scripts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="notify_on_info_alerts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="notify_on_warning_alerts",
            field=models.BooleanField(default=False),
        ),
    ]
