# Generated by Django 4.2.11 on 2024-04-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_urlaction_action_type_urlaction_rest_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="enable_server_scripts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="enable_server_webterminal",
            field=models.BooleanField(default=True),
        ),
    ]
