# Generated by Django 4.2.13 on 2024-06-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_coresettings_enable_server_scripts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlaction",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="urlaction",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
