# Generated by Django 4.2.13 on 2024-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_coresettings_notify_on_info_alerts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coresettings",
            name="notify_on_warning_alerts",
            field=models.BooleanField(default=True),
        ),
    ]
