# Generated by Django 4.2.13 on 2024-06-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_urlaction_rest_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coresettings",
            name="enable_server_webterminal",
            field=models.BooleanField(default=False),
        ),
    ]
