# Generated by Django 4.2.14 on 2024-09-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_coresettings_notify_on_warning_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='block_local_user_logon',
            field=models.BooleanField(default=True),
        ),
    ]
