# Generated by Django 4.2.14 on 2024-10-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_coresettings_block_local_user_logon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='disable_sso',
            field=models.BooleanField(default=True),
        ),
    ]
