# Generated by Django 4.2.20 on 2025-06-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_schedule_alter_coresettings_default_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='report_history_prune_days',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
