# Generated by Django 4.2.16 on 2024-10-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_coresettings_disable_sso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coresettings",
            name="block_local_user_logon",
            field=models.BooleanField(default=False),
        ),
    ]
