# Generated by Django 4.2.22 on 2026-02-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_coresettings_default_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="default_shell_darwin",
            field=models.CharField(
                choices=[("bash", "bash"), ("custom", "custom")],
                default="bash",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="default_shell_darwin_custom",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="default_shell_linux",
            field=models.CharField(
                choices=[("bash", "bash"), ("custom", "custom")],
                default="bash",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="default_shell_linux_custom",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="default_shell_windows",
            field=models.CharField(
                choices=[
                    ("cmd", "cmd"),
                    ("powershell", "powershell"),
                    ("custom", "custom"),
                ],
                default="cmd",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="default_shell_windows_custom",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
