# Generated by Django 4.2.20 on 2025-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_coresettings_report_history_prune_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresettings',
            name='report_history_prune_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=15),
        ),
    ]
