# Generated by Django 4.2.26 on 2025-12-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_coresettings_default_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="branding",
            field=models.JSONField(default=dict),
        ),
    ]
