# Generated by Django 4.2.22 on 2026-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_coresettings_default_shell_darwin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="terminal_mode",
            field=models.CharField(
                choices=[
                    ("new", "Use new terminal"),
                    ("legacy", "Use legacy terminal"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
