# Generated by Django 4.2.27 on 2026-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_coresettings_enable_ssh_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ssh_gateway_enable_exec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ssh_gateway_enable_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ssh_gateway_enable_terminal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ssh_gateway_max_sessions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ssh_gateway_session_timeout',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
