# Generated by Django 4.2.30 on 2026-07-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0062_agent_default_shell_agent_default_shell_custom'),
        ('core', '0054_aiprovider_coresettings_ai_module_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('allow_mutating', models.BooleanField(default=False)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('daily', 'Daily')], default='interval', max_length=20)),
                ('interval_minutes', models.PositiveIntegerField(default=60)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('alert_threshold', models.CharField(choices=[('never', 'Never alert'), ('warning', 'Alert on Warning or Alert'), ('alert', 'Alert only on Alert')], default='alert', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_summary', models.TextField(blank=True, null=True)),
                ('last_output', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='agents.agent')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
