# Generated by Django 4.2.30 on 2026-07-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_aitask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('triggered_by', models.CharField(default='schedule', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.aitask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
