# Generated by Django 4.2.30 on 2026-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_aitaskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='schedule_type',
            field=models.CharField(choices=[('interval', 'Interval'), ('daily', 'Daily'), ('once', 'One time')], default='interval', max_length=20),
        ),
    ]
