# Generated by Django 4.2.30 on 2026-07-08 12:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_deployment_goarch'),
        ('agents', '0062_agent_default_shell_agent_default_shell_custom'),
        ('core', '0057_aitask_run_at_alter_aitask_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaskrun',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='aitaskrun',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.aitask'),
        ),
        migrations.CreateModel(
            name='BulkAICommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('allow_mutating', models.BooleanField(default=False)),
                ('alert_threshold', models.CharField(choices=[('never', 'Never alert'), ('warning', 'Alert on Warning or Alert'), ('alert', 'Alert only on Alert')], default='alert', max_length=20)),
                ('schedule_type', models.CharField(choices=[('interval', 'Every N hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='interval', max_length=20)),
                ('interval_hours', models.PositiveIntegerField(default=24)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('weekly_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, null=True, size=7)),
                ('monthly_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('target', models.CharField(default='all', max_length=20)),
                ('mon_type', models.CharField(default='all', max_length=20)),
                ('os_type', models.CharField(default='all', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_count', models.PositiveIntegerField(default=0)),
                ('agents', models.ManyToManyField(blank=True, related_name='bulk_ai_commands', to='agents.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodel')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aitaskrun',
            name='bulk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.bulkaicommand'),
        ),
    ]
