# Generated by Django 4.2.30 on 2026-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_aitaskrun_agent_alter_aitaskrun_task_bulkaicommand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkaicommand',
            name='filters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
