# Generated by Django 4.2.30 on 2026-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_bulkaicommand_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkaicommand',
            name='run_mode',
            field=models.CharField(default='schedule', max_length=20),
        ),
    ]
