# Generated by Django 4.2.30 on 2026-07-08 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_bulkaicommand_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='monthly_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='run_mode',
            field=models.CharField(default='schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='aitask',
            name='weekly_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, null=True, size=7),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='schedule_type',
            field=models.CharField(choices=[('interval', 'Interval'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('once', 'One time')], default='interval', max_length=20),
        ),
    ]
