# Generated by Django 4.2.30 on 2026-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_aitask_monthly_day_aitask_next_run_aitask_run_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkaicommand',
            name='filter_match',
            field=models.CharField(default='any', max_length=8),
        ),
    ]
