# Generated by Django 4.2.30 on 2026-07-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_bulkaicommand_filter_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkaicommand',
            name='exclude_agent_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
