# Generated by Django 4.2.30 on 2026-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_bulkaicommand_exclude_agent_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_helpdesk_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
