# Generated by Django 4.2.30 on 2026-07-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_coresettings_ai_helpdesk_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_helpdesk_api_base_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_helpdesk_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
