# Generated by Django 4.2.30 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_coresettings_ai_helpdesk_api_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaskrun',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bulkaicommand',
            name='report_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
