# Generated by Django 4.2.30 on 2026-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_aitaskrun_batch_id_bulkaicommand_report_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_helpdesk_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
