# Generated by Django 4.2.30 on 2026-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_coresettings_ai_helpdesk_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_alerts_only_on_ticket_error',
            field=models.BooleanField(default=False),
        ),
    ]
