# Generated by Django 4.2.30 on 2026-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_coresettings_ai_alerts_only_on_ticket_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_automation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_triage_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AITicketState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=400)),
                ('requester', models.CharField(blank=True, default='', max_length=255)),
                ('is_alert', models.BooleanField(default=False)),
                ('status', models.CharField(default='new', max_length=30)),
                ('classification', models.CharField(blank=True, default='', max_length=40)),
                ('summary', models.TextField(blank=True, default='')),
                ('proposed_action', models.TextField(blank=True, default='')),
                ('last_change_seen', models.CharField(blank=True, default='', max_length=64)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_aitick_status_cf816e_idx')],
            },
        ),
    ]
