# Generated by Django 4.2.30 on 2026-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_coresettings_ai_ticket_automation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_act_on_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
