# Generated by Django 4.2.30 on 2026-07-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_coresettings_ai_ticket_act_on_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_client_map',
            field=models.TextField(blank=True, default=''),
        ),
    ]
