# Generated by Django 4.2.30 on 2026-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_coresettings_ai_ticket_client_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecisionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ticket_ref', models.CharField(max_length=100)),
                ('question', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_aideci_status_1019bb_idx')],
            },
        ),
    ]
