# Generated by Django 4.2.30 on 2026-07-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0063_agent_ai_notes'),
        ('core', '0072_aidecisionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScheduledAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(blank=True, default='', max_length=100)),
                ('action', models.TextField()),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('allow_mutating', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('result', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_scheduled_actions', to='agents.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'run_at'], name='core_aische_status_15543c_idx')],
            },
        ),
    ]
