# Generated by Django 4.2.30 on 2026-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_aischeduledaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_decision_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
