# Generated by Django 4.2.30 on 2026-07-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_coresettings_ai_ticket_decision_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketstate',
            name='assignee_seen',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aiticketstate',
            name='last_message_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
