# Generated by Django 4.2.30 on 2026-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_aiticketstate_assignee_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketstate',
            name='partner_checked',
            field=models.BooleanField(default=False),
        ),
    ]
