# Generated by Django 4.2.30 on 2026-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_aiticketstate_partner_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketstate',
            name='last_triaged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
