# Generated by Django 4.2.30 on 2026-07-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_aiticketstate_last_triaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedures_backfill_days',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedures_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedures_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedures_last_mined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedures_mining_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedures_mining_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AIProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('applies_to', models.CharField(blank=True, default='', max_length=400)),
                ('symptom', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('fix', models.TextField(blank=True, default='')),
                ('verification', models.TextField(blank=True, default='')),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('source_ticket_refs', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.CharField(default='low', max_length=10)),
                ('origin', models.CharField(choices=[('ai_mined', 'AI mined from closed tickets'), ('ai_resolution', 'AI captured on resolve'), ('human', 'Human authored')], default='ai_mined', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('retired', 'Retired')], default='draft', max_length=10)),
                ('updated_by', models.CharField(blank=True, default='', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
                'indexes': [models.Index(fields=['category'], name='core_aiproc_categor_8678fb_idx'), models.Index(fields=['status'], name='core_aiproc_status_d345b0_idx')],
            },
        ),
    ]
