# Generated by Django 4.2.30 on 2026-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_coresettings_ai_procedures_backfill_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMinedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(max_length=100, unique=True)),
                ('last_change_seen', models.CharField(blank=True, default='', max_length=64)),
                ('mined_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
