# Generated by Django 4.2.30 on 2026-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_aiminedticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_verifier_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_verifiers_dry_run',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_verifiers_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
