# Generated by Django 4.2.30 on 2026-07-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_coresettings_ai_verifier_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_model_catalog',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_model_catalog_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_model_catalog_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_model_catalog_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
