# Generated by Django 4.2.30 on 2026-07-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_coresettings_ai_model_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_model_autoregister',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_days',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_last_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_last_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_max_wait_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_target',
            field=models.CharField(blank=True, default='latest', max_length=32),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_time',
            field=models.CharField(blank=True, default='03:30', max_length=5),
        ),
    ]
