# Generated by Django 4.2.30 on 2026-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_coresettings_ai_model_autoregister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_runtime_update_blocked_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
