# Generated by Django 4.2.30 on 2026-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_coresettings_ai_runtime_update_blocked_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_all_teams',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_last_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_recipients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_time',
            field=models.CharField(blank=True, default='07:00', max_length=5),
        ),
    ]
