# Generated by Django 4.2.30 on 2026-07-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_coresettings_ai_daily_report_all_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_report_baseline_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_report_fallback_minutes',
            field=models.TextField(blank=True, default='{"alert_clean": 4, "alert_actionable": 15, "regular": 25, "unknown": 10}'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_report_max_session_minutes',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_report_min_session_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_report_minutes_per_message',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_report_session_gap_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
