# Generated by Django 4.2.30 on 2026-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_coresettings_ai_report_baseline_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_ai_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_daily_report_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
