# Generated by Django 4.2.30 on 2026-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_coresettings_ai_daily_report_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='reply_register',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
