# Generated by Django 4.2.30 on 2026-07-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_aitask_reply_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnownCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_key', models.CharField(max_length=120)),
                ('customer_key', models.CharField(blank=True, default='', max_length=200)),
                ('host', models.CharField(blank=True, default='', max_length=200)),
                ('tracker_ref', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(choices=[('advising', 'Waiting for someone to tell the customer'), ('advised', 'Customer has been told; repeats are suppressed'), ('resolved', 'Stopped recurring'), ('muted', 'Deliberately ignored by a human')], default='advising', max_length=20)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('suppressed', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('advised_at', models.DateTimeField(blank=True, null=True)),
                ('last_ticket_ref', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='auto_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='condition_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='disposition',
            field=models.CharField(blank=True, choices=[('', 'None (advice only)'), ('benign', 'Proven harmless - may be cancelled'), ('customer_action', 'Real, and the customer must act'), ('our_action', 'Real, and we must act'), ('needs_human', 'Cannot be ruled automatically')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='evidence',
            field=models.CharField(choices=[('none', 'Advice only'), ('notification', 'The notification proves it'), ('device', 'Read-only probe on the device')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='match',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='probe',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='repeat_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='aiprocedure',
            index=models.Index(fields=['condition_key'], name='core_aiproc_conditi_255a9b_idx'),
        ),
        migrations.AddField(
            model_name='aiknowncondition',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='core.aiprocedure'),
        ),
        migrations.AddIndex(
            model_name='aiknowncondition',
            index=models.Index(fields=['condition_key'], name='core_aiknow_conditi_9e3e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowncondition',
            index=models.Index(fields=['state'], name='core_aiknow_state_c7342d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiknowncondition',
            unique_together={('condition_key', 'customer_key', 'host')},
        ),
    ]
