# Generated by Django 4.2.30 on 2026-07-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_aiknowncondition_aiprocedure_auto_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_ai_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_include_assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_last_result',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_recipients',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_review_time',
            field=models.CharField(default='09:00', max_length=5),
        ),
    ]
