# Generated by Django 4.2.30 on 2026-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_coresettings_ai_ticket_review_ai_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(db_index=True, max_length=100)),
                ('actor_username', models.CharField(max_length=150)),
                ('actor_display', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(max_length=40)),
                ('surface', models.CharField(choices=[('decision_chat', 'Ticket chat (human driving)'), ('device_chat', 'Device chat (human driving)'), ('unattended', 'Unattended run (no human)')], default='decision_chat', max_length=20)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('at', models.DateTimeField()),
                ('source', models.CharField(default='live', max_length=40)),
                ('detail', models.CharField(blank=True, default='', max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['ticket_ref', 'at'], name='core_aiacti_ticket__751902_idx'), models.Index(fields=['actor_username'], name='core_aiacti_actor_u_a5d205_idx')],
            },
        ),
    ]
