# Generated by Django 4.2.30 on 2026-07-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_aiactioncredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocedure',
            name='baseline_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_work_away_credit_minutes',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_work_idle_cap_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_work_lead_in_minutes',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_work_tail_minutes',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='TicketWorkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('agent_id', models.CharField(blank=True, default='', max_length=200)),
                ('actor_kind', models.CharField(choices=[('tech', 'Technician working directly'), ('tech_via_ai', 'Technician driving the AI'), ('ai_unattended', 'AI with nobody driving')], max_length=20)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_display', models.CharField(blank=True, default='', max_length=200)),
                ('surface', models.CharField(choices=[('ticket_chat', 'Ticket (AI-decision) chat'), ('device_chat', 'Device chat / pichat'), ('helpdesk_direct', 'Worked directly in the helpdesk'), ('unattended_task', 'Scheduled AI task'), ('verifier', 'Alert verifier'), ('condition_engine', 'Known-condition engine')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('human_minutes', models.FloatField(blank=True, null=True)),
                ('ai_minutes', models.FloatField(default=0)),
                ('confidence', models.CharField(choices=[('measured', 'Measured from timestamps'), ('sessionized', 'Derived from event bursts'), ('estimated', 'Estimated - no duration evidence')], default='estimated', max_length=12)),
                ('method', models.CharField(blank=True, default='', max_length=120)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='live', max_length=40)),
                ('overlaps_ids', models.JSONField(blank=True, default=list)),
                ('overlap_minutes', models.FloatField(default=0)),
                ('baseline_minutes', models.FloatField(blank=True, null=True)),
                ('baseline_source', models.CharField(blank=True, default='', max_length=200)),
                ('saved_minutes', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.ticketworkentry')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['ticket_ref', 'started_at'], name='core_ticket_ticket__295fd1_idx'), models.Index(fields=['actor_username', 'started_at'], name='core_ticket_actor_u_dbfd2c_idx'), models.Index(fields=['actor_kind'], name='core_ticket_actor_k_39c6a4_idx')],
            },
        ),
    ]
