# Generated by Django 4.2.30 on 2026-07-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_aiprocedure_baseline_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_work_actor_aliases',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
