# Generated by Django 4.2.30 on 2026-07-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_coresettings_ai_work_actor_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketworkentry',
            name='surface',
            field=models.CharField(choices=[('ticket_chat', 'Ticket (AI-decision) chat'), ('device_chat', 'Device chat / pichat'), ('helpdesk_direct', 'Worked directly in the helpdesk'), ('unattended_task', 'Scheduled AI task'), ('verifier', 'Alert verifier'), ('condition_engine', 'Known-condition engine'), ('rmm_activity', 'Working in RMM (remote sessions, device work)')], max_length=20),
        ),
    ]
