# Generated by Django 4.2.30 on 2026-07-26 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0093_alter_ticketworkentry_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactioncredit',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_action_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketworkentry',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticketworkentry',
            index=models.Index(fields=['actor_user', 'started_at'], name='core_ticket_actor_u_0c0ffb_idx'),
        ),
    ]
