# Generated by Django 4.2.30 on 2026-07-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_aiactioncredit_actor_user_ticketworkentry_actor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_work_compose_chars_per_min',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_work_read_chars_per_min',
            field=models.PositiveIntegerField(default=900),
        ),
    ]
