# Generated by Django 4.2.30 on 2026-07-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_coresettings_ai_work_compose_chars_per_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_staff_email_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_staff_extra_usernames',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
