# Generated by Django 4.2.30 on 2026-07-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_coresettings_ai_staff_email_domains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('activity', 'Activity report - what happened'), ('open_tickets', 'Open-ticket review - what could be done')], default='activity', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('cadence', models.CharField(choices=[('daily', 'Every day'), ('weekdays', 'Weekdays only (Mon-Fri)'), ('weekly', 'Once a week'), ('monthly', 'Once a month')], default='daily', max_length=12)),
                ('run_at', models.CharField(default='07:55', max_length=5)),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('window_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('recipients', models.CharField(blank=True, default='', max_length=500)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, default='', max_length=1000)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'run_at', 'name'],
            },
        ),
    ]
