# Generated by Django 3.1.3 on 2020-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotasks", "0008_auto_20201030_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="automatedtask",
            name="run_time_bit_weekdays",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
