# Generated by Django 3.1.4 on 2021-01-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0012_auto_20210128_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='alert_severity',
            field=models.CharField(choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=30),
        ),
    ]
