# Generated by Django 3.1.4 on 2021-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0014_automatedtask_dashboard_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='resolved_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='resolved_text_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
