# Generated by Django 3.2.1 on 2021-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_auto_20210614_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='agent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
