# Generated by Django 3.2.6 on 2021-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0018_auto_20210905_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
