# Generated by Django 4.0.4 on 2022-04-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0023_alter_pendingaction_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingaction',
            name='cancelable',
        ),
        migrations.RemoveField(
            model_name='pendingaction',
            name='celery_id',
        ),
    ]
