FROM nginxinc/nginx-unprivileged:stable-alpine

ENV TACTICAL_DIR /opt/tactical

USER root

RUN apk add --no-cache openssl bash

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

COPY docker/containers/tactical-nginx/entrypoint.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/entrypoint.sh

USER nginx

EXPOSE 443 80