FROM tiangolo/uwsgi-nginx:python3.7

WORKDIR /app

ARG DJANGO_SEKRET
ARG DJANGO_DEBUG
ARG POSTGRES_USER
ARG POSTGRES_PASS
ARG POSTGRES_HOST
ARG SALT_HOST
ARG SALT_USER
ARG SALT_PASS
ARG REDIS_HOST
ARG MESH_USER
ARG MESH_HOST
ARG MESH_TOKEN_KEY
ARG APP_HOST
ARG API_HOST
ARG ADMIN_URL
ARG EMAIL_TLS
ARG EMAIL_HOST
ARG EMAIL_USER
ARG EMAIL_PASS
ARG EMAIL_PORT
ARG EMAIL_RECIPIENTS

EXPOSE 80

RUN apt-get update && apt-get install -y gettext-base
COPY ./api/tacticalrmm/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./api/tacticalrmm/ .
COPY ./docker/api/prestart.sh .
COPY ./docker/api/uwsgi.ini .
COPY ./docker/api/api.conf /app/api.conf.tmp
RUN envsubst '\$APP_HOST, \$API_HOST' < /app/api.conf.tmp > /app/nginx.conf && \
    rm /app/api.conf.tmp
COPY ./docker/api/local_settings.py.keep ./tacticalrmm/local_settings.py.tmp
RUN envsubst < /app/tacticalrmm/local_settings.py.tmp > /app/tacticalrmm/local_settings.py && rm /app/tacticalrmm/local_settings.py.tmp

COPY ./_modules /srv/salt/_modules
COPY ./scripts /srv/salt/scripts
RUN mkdir /srv/salt/scripts/userdefined && \
    chown -R 1000:nginx /srv/salt/scripts/userdefined && \
    chmod -R 771 /srv/salt/scripts/userdefined
    