# Generated by Django 3.0.6 on 2020-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_auto_20200531_2058"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="checks_last_generated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
