# Generated by Django 3.0.7 on 2020-06-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_auto_20200609_1607"),
        ("agents", "0004_auto_20200604_1721"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="automation.Policy",
            ),
        ),
    ]
