# Generated by Django 3.1.1 on 2020-09-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0015_auto_20200922_1344"),
        ("agents", "0015_note"),
    ]

    operations = []
