# Generated by Django 3.1.7 on 2021-03-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20210217_1736'),
        ('agents', '0030_agent_offline_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='alert_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='alerts.alerttemplate'),
        ),
    ]
