# Generated by Django 3.2.12 on 2022-02-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_alter_agent_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='antivirus',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='local_ip',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='used_ram',
        ),
    ]
