# Generated by Django 3.2.12 on 2022-02-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0043_auto_20220227_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='salt_id',
            new_name='goarch',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='salt_ver',
        ),
    ]
