# Generated by Django 4.2.3 on 2023-07-18 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_coresettings_open_ai_model_and_more"),
        ("agents", "0056_alter_agent_time_zone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agentcustomfield",
            unique_together={("agent", "field")},
        ),
    ]
