# Generated by Django 3.1 on 2020-08-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingaction",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
