# Generated by Django 3.1.1 on 2020-09-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_auto_20200810_0544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingaction",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("schedreboot", "Scheduled Reboot"),
                    ("taskaction", "Scheduled Task Action"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
