# Generated by Django 3.2.1 on 2021-06-14 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0012_auto_20210228_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="debuglog",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debuglogs",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="debuglog",
            name="entry_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="debuglog",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("critical", "Critical"),
                ],
                default="info",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="debuglog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("agent_update", "Agent Update"),
                    ("agent_issues", "Agent Issues"),
                    ("win_updates", "Windows Updates"),
                    ("system_issues", "System Issues"),
                    ("scripting", "Scripting"),
                ],
                default="system_issues",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="debuglog",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
