# Generated by Django 4.2.10 on 2024-02-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0024_remove_pendingaction_cancelable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="debuglog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
