# Generated by Django 3.2.2 on 2021-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_urlaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='clear_faults_days',
            field=models.IntegerField(default=0),
        ),
    ]
