# Generated by Django 3.2.1 on 2021-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210707_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='audit_log_prune_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
