# Generated by Django 4.2.9 on 2024-01-28 03:01

from django.db import migrations


def update_hide_in_summary(apps, schema_editor):
    CustomField = apps.get_model("core", "CustomField")
    for field in CustomField.objects.filter(hide_in_ui=True):
        field.hide_in_summary = True
        field.save(update_fields=["hide_in_summary"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_customfield_hide_in_summary"),
    ]

    operations = [migrations.RunPython(update_hide_in_summary)]
