# Generated by Django 4.2.10 on 2024-02-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20240128_0301"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="mesh_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
