# Generated by Django 4.2.11 on 2024-03-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_coresettings_sync_mesh_with_trmm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coresettings",
            name="mesh_disable_auto_login",
        ),
    ]
