# Generated by Django 4.2.14 on 2024-07-28 02:25

from django.db import migrations, models
import systray.models
import systray.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.FileField(blank=True, null=True, storage=systray.utils.get_systray_assets_fs, unique=True, upload_to='', validators=[systray.models.validate_ico_file])),
            ],
        ),
    ]
