# Generated by Django 3.0.6 on 2020-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check'), ('winsvc', 'Win Service Check'), ('script', 'Script Check'), ('eventlog', 'Event Log Check')], default='diskspace', max_length=50),
        ),
    ]
