# Generated by Django 2.2.3 on 2019-07-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=30)),
                ('disk', models.CharField(max_length=2, null=True)),
                ('disk_threshold', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(default='N/A', max_length=30)),
                ('email_alert', models.BooleanField(default=False)),
                ('text_alert', models.BooleanField(default=False)),
                ('more_info', models.TextField(null=True)),
                ('ping_ip', models.CharField(max_length=255, null=True)),
                ('ping_name', models.CharField(max_length=255, null=True)),
                ('ping_failures', models.PositiveIntegerField(null=True)),
                ('ping_failure_count', models.IntegerField(null=True)),
                ('mem_threshold', models.PositiveIntegerField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardcheck', to='agents.Agent')),
            ],
        ),
    ]
