# Generated by Django 3.0.5 on 2020-04-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingcheck',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scriptcheck',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
