# Generated by Django 3.0.6 on 2020-05-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_auto_20200530_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='svc_policy_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
