# Generated by Django 3.0.5 on 2020-04-06 00:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_auto_20200405_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryhistory',
            name='agent',
        ),
        migrations.AddField(
            model_name='cpuloadcheck',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpuloadcheck',
            name='failures',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cpuloadcheck',
            name='history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='memcheck',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memcheck',
            name='failures',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='memcheck',
            name='history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='CpuHistory',
        ),
        migrations.DeleteModel(
            name='MemoryHistory',
        ),
    ]
