# Generated by Django 3.0.5 on 2020-04-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automatedtask'),
        ('checks', '0005_auto_20200406_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuloadcheck',
            name='task_on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpuloadtaskfailure', to='automation.AutomatedTask'),
        ),
        migrations.AddField(
            model_name='diskcheck',
            name='task_on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disktaskfailure', to='automation.AutomatedTask'),
        ),
        migrations.AddField(
            model_name='memcheck',
            name='task_on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memtaskfailure', to='automation.AutomatedTask'),
        ),
        migrations.AddField(
            model_name='pingcheck',
            name='task_on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pingtaskfailure', to='automation.AutomatedTask'),
        ),
        migrations.AddField(
            model_name='scriptcheck',
            name='task_on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripttaskfailure', to='automation.AutomatedTask'),
        ),
        migrations.AddField(
            model_name='winservicecheck',
            name='task_on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winsvctaskfailure', to='automation.AutomatedTask'),
        ),
    ]
