# Generated by Django 3.0.5 on 2020-04-15 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('checks', '0005_auto_20200406_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuloadcheck',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpuloadchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='diskcheck',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diskchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='memcheck',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='pingcheck',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pingchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='scriptcheck',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scriptchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='winservicecheck',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winservicechecks', to='automation.Policy'),
        ),
    ]
