# Generated by Django 3.1 on 2020-08-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0005_auto_20200810_0544"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="event_id_is_wildcard",
            field=models.BooleanField(default=False),
        ),
    ]
