# Generated by Django 3.0.5 on 2020-04-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automatedtask'),
        ('checks', '0006_auto_20200410_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuloadcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='diskcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='memcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='pingcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='scriptcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='winservicecheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.Policy'),
        ),
    ]
