# Generated by Django 3.1 on 2020-08-30 05:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0006_check_event_id_is_wildcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="script_args",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
