# Generated by Django 3.1.1 on 2020-09-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0007_check_script_args"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="pass_if_svc_not_exist",
            field=models.BooleanField(default=False),
        ),
    ]
