# Generated by Django 2.2.6 on 2019-10-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0010_pingcheck_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskcheck',
            name='last_run',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pingcheck',
            name='last_run',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
