# Generated by Django 3.1.3 on 2020-12-04 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0010_auto_20200922_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='alert_severity',
            field=models.CharField(choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=15),
        ),
        migrations.AddField(
            model_name='check',
            name='error_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='check',
            name='warning_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
