# Generated by Django 3.0.5 on 2020-04-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0007_auto_20200415_2300'),
        ('checks', '0010_auto_20200414_0332'),
    ]

    operations = [
    ]
