# Generated by Django 2.2.6 on 2019-10-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0011_auto_20191013_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuloadcheck',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check')], default='cpuload', max_length=30),
        ),
        migrations.AlterField(
            model_name='cpuloadcheck',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpuloadcheck',
            name='status',
            field=models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
