# Generated by Django 3.0.5 on 2020-04-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20200416_0242'),
        ('agents', '0001_initial'),
        ('checks', '0011_merge_20200416_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuloadcheck',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpuloadchecks', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='cpuloadcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpuloadchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='diskcheck',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diskchecks', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='diskcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diskchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='memcheck',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memchecks', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='memcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='pingcheck',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pingchecks', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='pingcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pingchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='scriptcheck',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scriptchecks', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='scriptcheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scriptchecks', to='automation.Policy'),
        ),
        migrations.AlterField(
            model_name='winservicecheck',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winservicechecks', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='winservicecheck',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winservicechecks', to='automation.Policy'),
        ),
    ]
