# Generated by Django 2.2.6 on 2019-10-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0012_auto_20191013_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuloadcheck',
            name='last_run',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
