# Generated by Django 3.1.4 on 2021-01-23 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0015_auto_20210110_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='threshold',
        ),
        migrations.AddField(
            model_name='check',
            name='alert_severity',
            field=models.CharField(choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=15),
        ),
        migrations.AddField(
            model_name='check',
            name='error_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='info_return_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='check',
            name='warning_return_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='check',
            name='warning_threshold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
