# Generated by Django 3.1.4 on 2021-01-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0015_auto_20210110_1808'),
        ('checks', '0011_auto_20201204_2302'),
    ]

    operations = [
    ]
