# Generated by Django 2.2.6 on 2019-10-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0015_memcheckemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='memcheck',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check')], default='memory', max_length=30),
        ),
    ]
