# Generated by Django 3.1.4 on 2021-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0016_merge_20210112_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='error_threshold',
        ),
        migrations.AlterField(
            model_name='check',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='warning_threshold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
