# Generated by Django 3.1.4 on 2021-01-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0017_auto_20210113_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='threshold',
            new_name='error_threshold',
        ),
    ]
