# Generated by Django 3.1.4 on 2021-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0018_auto_20210113_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='info_return_code',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='warning_return_code',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
