# Generated by Django 3.1.4 on 2021-01-20 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0019_auto_20210118_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='info_return_code',
        ),
        migrations.RemoveField(
            model_name='check',
            name='warning_return_code',
        ),
        migrations.AddField(
            model_name='check',
            name='info_return_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='check',
            name='warning_return_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
