# Generated by Django 3.1.7 on 2021-03-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0021_auto_20210212_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='number_of_events_b4_alert',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
