# Generated by Django 3.2.12 on 2022-03-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0026_auto_20220325_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhistory',
            name='agent_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
