# Generated by Django 3.2.12 on 2022-04-01 22:48

from django.db import migrations


def migrate_check_results(apps, schema_editor):
    Check = apps.get_model("checks", "Check")
    CheckResult = apps.get_model("checks", "CheckResult")
    for check in Check.objects.exclude(agent=None):
        CheckResult(
            assigned_check=check,
            agent=check.agent,
            status=check.status,
            more_info=check.more_info,
            last_run=check.last_run,
            fail_count=check.fail_count,
            outage_history=check.outage_history,
            extra_details=check.extra_details,
            stdout=check.stdout,
            stderr=check.stderr,
            retcode=check.retcode,
            execution_time=check.execution_time,
            history=check.history,
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0026_auto_20220401_2244"),
    ]

    operations = [
        migrations.RunPython(migrate_check_results),
    ]
