# Generated by Django 3.2.12 on 2022-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0027_checkhistory_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkhistory',
            name='agent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
