# Generated by Django 3.2.12 on 2022-03-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0046_alter_agenthistory_command'),
        ('checks', '0027_policycheckresults_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolicyCheckResults',
            new_name='PolicyCheckResult',
        ),
    ]
