# Generated by Django 4.1.3 on 2022-12-03 09:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0030_alter_checkresult_retcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="env_vars",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
