# Generated by Django 4.2.10 on 2024-02-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0031_check_env_vars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkhistory",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="checkresult",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
