# Generated by Django 4.2.20 on 2025-04-30 16:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0033_check_success_return_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="info_return_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="check",
            name="success_return_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveBigIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="check",
            name="warning_return_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
