apiVersion: v1
kind: ConfigMap
metadata:
  name: tactical-backend
data:
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_FROM: ""
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_TLS: ""
  TRMM_USER: ""
  TRMM_PASS: ""
  TACTICAL_BACKEND_PORT: "8000"
  TRMM_PROTO: "http"
  TRMM_DISABLE_WEB_TERMINAL: ""
  TRMM_DISABLE_SERVER_SCRIPTS: ""
  TRMM_DISABLE_SSO: ""
  TRMM_DISABLE_2FA: ""
  OPENFRAME_MODE: ""
  NODE_ENV: ""
  WS_PROTO: "ws"
  WS_MASK_OVERRIDE: ""
  TACTICAL_DIR: "/opt/tactical"
  TACTICAL_TMP_DIR: "/tmp/tactical"
  API_HOST: "tactical-backend-0.tactical-backend.{{ .Release.Namespace }}.svc.cluster.local:8000"
  APP_HOST: "tactical-frontend.{{ .Release.Namespace }}.svc.cluster.local:4443"
  NATS_CONFIG: "/opt/tactical/nats-rmm.conf"
  NATS_API_CONFIG: "/opt/tactical/nats-api.conf"
  NATS_CONFIG_CHECK_INTERVAL: ""
  NATS_STD_BIND_HOST: ""
  NATS_WEBSOCKET_PORT: "9235"
  NATS_WS_BIND_HOST: ""
  NATS_STANDARD_PORT: "4222"
  NATS_CONNECT_HOST: "tactical-nats.{{ .Release.Namespace }}.svc.cluster.local"
  NATS_WEBSOCKET_HOST: "tactical-websockets-0.tactical-websockets.{{ .Release.Namespace }}.svc.cluster.local"
  WEBSOCKETS_BIND_HOST: "tactical-websockets"
  WEBSOCKET_PORT: "8000"
  PUBLIC_DIR: "/usr/share/nginx/html"
  TACTICAL_READY_FILE: "/opt/tactical/tmp/tactical/ready"
  NGINX_HOST_IP: "tactical-nginx-0.tactical-nginx.{{ .Release.Namespace }}.svc.cluster.local"
  NGINX_HOST_PORT: "80"
