apiVersion: v1
kind: ConfigMap
metadata:
  name: tactical-datasources
data:
  POSTGRES_HOST: {{ .Values.postgres.external.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.external.port | quote }}

  REDIS_HOST: {{ .Values.redis.external.host | quote }}
  REDIS_PORT: {{ .Values.redis.external.port | quote }}

  NATS_HOST: {{ .Values.nats.external.host | quote }}
  NATS_PORT: {{ .Values.nats.external.port | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tactical-backend
data:
  TRMM_USER: ""
  TRMM_PASS: ""
  TACTICAL_BACKEND_PORT: {{ .Values.tactical.backend.port | quote }}
  TRMM_PROTO: "http"
  TRMM_DISABLE_WEB_TERMINAL: "False"
  TRMM_DISABLE_SERVER_SCRIPTS: "False"
  TRMM_DISABLE_SSO: "False"
  TRMM_DISABLE_2FA: "True"
  TRMM_DISABLE_MESH_SYNC_TASK: "True"
  OPENFRAME_MODE: "True"
  API_HOST: "tactical-backend-0.tactical-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.tactical.backend.port }}"
  APP_HOST: {{ .Values.tactical.appHost | default (printf "tactical-frontend.%s.svc.cluster.local:4443" .Release.Namespace) | quote }}
  NATS_STD_BIND_HOST: ""
  NATS_WEBSOCKET_PORT: "9235"
  NATS_WS_BIND_HOST: ""
