{{- if or (not .Values.postgres.external.existingConfigMap) (not .Values.redis.external.existingConfigMap) (not .Values.nats.external.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tactical-datasources-urls
data:
  {{- if not .Values.postgres.external.existingConfigMap }}
  {{ .Values.postgres.external.urlKey }}: {{ required "postgres.external.url is required when existingConfigMap is not set" .Values.postgres.external.url | quote }}
  {{- end }}
  {{- if not .Values.redis.external.existingConfigMap }}
  {{ .Values.redis.external.urlKey }}: {{ required "redis.external.url is required when existingConfigMap is not set" .Values.redis.external.url | quote }}
  {{- end }}
  {{- if not .Values.nats.external.existingConfigMap }}
  {{ .Values.nats.external.urlKey }}: {{ required "nats.external.url is required when existingConfigMap is not set" .Values.nats.external.url | quote }}
  {{- end }}
{{- end }}
