{{- if not .Values.postgres.external.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: tactical-datasources
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.external.user | b64enc | quote }}
  POSTGRES_DATABASE: {{ .Values.postgres.external.database | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.external.password | b64enc | quote }}
{{- end }}

---

{{- if not .Values.tactical.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: tactical-backend
type: Opaque
data:
  {{ .Values.tactical.secretKeyKey }}: {{ .Values.tactical.secretKeyValue | b64enc | quote }}
{{- end }}
