{{- if not .Values.tactical.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: tactical-backend
type: Opaque
data:
  SECRET_KEY: {{ .Values.tactical.secretKeyValue | b64enc | quote }}
{{- end }}
