# Generated by Django 2.2.7 on 2019-12-01 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0009_agent_antivirus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255, null=True)),
                ('kb', models.CharField(max_length=100, null=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('title', models.TextField(null=True)),
                ('needs_reboot', models.BooleanField(default=False)),
                ('installed', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agent')),
            ],
        ),
    ]
