# Generated by Django 2.2.7 on 2019-12-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agent_antivirus'),
        ('winupdate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='WinUpdate',
        ),
    ]
