# Generated by Django 3.0 on 2019-12-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0010_auto_20191209_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winupdatepolicy',
            old_name='run_time_day',
            new_name='run_time_days',
        ),
    ]
