# Generated by Django 3.0 on 2019-12-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0011_auto_20191209_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winupdatepolicy',
            name='reprocess_failed_times',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
