# Generated by Django 3.0 on 2019-12-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0012_auto_20191209_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='winupdate',
            name='date_installed',
            field=models.DateTimeField(null=True),
        ),
    ]
