# Generated by Django 3.1.7 on 2021-03-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20210329_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcustomfield',
            old_name='checkbox_value',
            new_name='bool_value',
        ),
        migrations.RenameField(
            model_name='clientcustomfield',
            old_name='value',
            new_name='string_value',
        ),
        migrations.RemoveField(
            model_name='sitecustomfield',
            name='value',
        ),
    ]
