# Generated by Django 2.2.3 on 2019-07-07 00:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(max_length=255)),
                ('plat', models.CharField(max_length=255, null=True)),
                ('plat_release', models.CharField(max_length=255, null=True)),
                ('system_info', models.TextField(null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('local_ip', models.TextField()),
                ('agent_id', models.CharField(max_length=200)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('services', django.contrib.postgres.fields.jsonb.JSONField()),
                ('public_ip', models.CharField(max_length=100)),
                ('cpu_load', models.FloatField(null=True)),
                ('total_ram', models.IntegerField(null=True)),
                ('used_ram', models.IntegerField(null=True)),
                ('disks', django.contrib.postgres.fields.jsonb.JSONField()),
                ('boot_time', models.FloatField(null=True)),
                ('logged_in_username', models.CharField(max_length=200)),
                ('cpu_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('client', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=150)),
                ('monitoring_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255, null=True)),
                ('mesh_node_id', models.CharField(max_length=255, null=True)),
                ('overdue_email_alert', models.BooleanField(default=False)),
                ('overdue_text_alert', models.BooleanField(default=False)),
                ('overdue_time', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
