# Generated by Django 3.0.3 on 2020-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='ping_check_interval',
        ),
        migrations.AddField(
            model_name='agent',
            name='check_interval',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
