# Generated by Django 2.2.4 on 2019-09-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_uninstall_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='uninstall_inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
