# Generated by Django 3.0.3 on 2020-02-23 07:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200206_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='wmi_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
