# Generated by Django 3.0.6 on 2020-05-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentoutage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
