# Generated by Django 3.0.6 on 2020-05-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20200515_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentoutage',
            old_name='email_sent',
            new_name='outage_email_sent',
        ),
        migrations.RenameField(
            model_name='agentoutage',
            old_name='sms_sent',
            new_name='outage_sms_sent',
        ),
        migrations.AddField(
            model_name='agentoutage',
            name='recovery_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentoutage',
            name='recovery_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
