# Generated by Django 3.0.7 on 2020-06-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agent_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="uninstall_inprogress",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="uninstall_pending",
        ),
    ]
