# Generated by Django 3.0.7 on 2020-06-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='policies_pending',
        ),
    ]
