# Generated by Django 3.0.7 on 2020-06-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20200614_0850'),
        ('agents', '0006_remove_agent_policies_pending'),
    ]

    operations = [
    ]
