# Generated by Django 3.0.7 on 2020-06-15 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_auto_20200614_0850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="policies_pending",
        ),
    ]
