# Generated by Django 2.2.7 on 2019-11-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20191027_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='version',
            field=models.CharField(default='0.1.0', max_length=255),
        ),
    ]
