# Generated by Django 2.2.7 on 2019-12-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agent_antivirus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='public_ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
