# Generated by Django 2.2.7 on 2019-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_auto_20191201_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='patches_pending',
            field=models.BooleanField(default=False),
        ),
    ]
