# Generated by Django 3.1 on 2020-08-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_recoveryaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="disks",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="services",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="wmi_detail",
            field=models.JSONField(null=True),
        ),
    ]
