# Generated by Django 3.0 on 2019-12-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agent_patches_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='patches_pending',
        ),
    ]
