# Generated by Django 3.1.1 on 2020-09-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0013_agent_patches_last_installed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="managed_by_wsus",
        ),
    ]
