# Generated by Django 3.0 on 2019-12-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agent_needs_reboot'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='managed_by_wsus',
            field=models.BooleanField(default=False),
        ),
    ]
