# Generated by Django 3.0 on 2019-12-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agent_managed_by_wsus'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_updating',
            field=models.BooleanField(default=False),
        ),
    ]
