# Generated by Django 3.0.2 on 2020-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_remove_agent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='choco_installed',
            field=models.BooleanField(default=False),
        ),
    ]
