# Generated by Django 3.1.2 on 2020-10-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0016_merge_20200923_0225"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="salt_update_pending",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="update_pending",
        ),
        migrations.AlterField(
            model_name="agent",
            name="boot_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="disks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="local_ip",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="mesh_node_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="operating_system",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="services",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="used_ram",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="wmi_detail",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
