# Generated by Django 3.1.2 on 2020-10-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0017_auto_20201016_0629"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="last_logged_in_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="logged_in_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="plat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="plat_release",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="total_ram",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
