# Generated by Django 3.1.2 on 2020-10-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0019_agent_maintenace_mode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="maintenace_mode",
            new_name="maintenance_mode",
        ),
    ]
