# Generated by Django 3.1.2 on 2020-11-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_deployment'),
        ('agents', '0020_auto_20201025_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='client',
        ),
        migrations.AlterField(
            model_name='agent',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='clients.site'),
        ),
    ]
