# Generated by Django 3.1.2 on 2020-11-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0023_auto_20201101_2312"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="site_link",
            new_name="site",
        ),
    ]
