# Generated by Django 3.1.3 on 2020-11-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0024_auto_20201101_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recoveryaction",
            name="mode",
            field=models.CharField(
                choices=[
                    ("salt", "Salt"),
                    ("mesh", "Mesh"),
                    ("command", "Command"),
                    ("rpc", "Nats RPC"),
                ],
                default="mesh",
                max_length=50,
            ),
        ),
    ]
