# Generated by Django 3.1.4 on 2021-01-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0026_auto_20201125_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='overdue_dashboard_alert',
            field=models.BooleanField(default=False),
        ),
    ]
