# Generated by Django 3.1.4 on 2021-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_agent_overdue_dashboard_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentoutage',
            name='outage_email_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentoutage',
            name='outage_sms_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
