# Generated by Django 3.1.7 on 2021-03-29 02:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0032_agentcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcustomfield',
            name='multiple_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
