# Generated by Django 3.1.7 on 2021-03-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0034_agentcustomfield_checkbox_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcustomfield',
            old_name='checkbox_value',
            new_name='bool_value',
        ),
        migrations.RenameField(
            model_name='agentcustomfield',
            old_name='value',
            new_name='string_value',
        ),
    ]
