# Generated by Django 3.1.7 on 2021-04-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0035_auto_20210329_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='block_policy_inheritance',
            field=models.BooleanField(default=False),
        ),
    ]
