# Generated by Django 3.2.1 on 2021-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0036_agent_block_policy_inheritance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_run', 'Task Run'), ('script_run', 'Script Run'), ('cmd_run', 'CMD Run')], default='cmd_run', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='mesh', max_length=50)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('results', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
