# Generated by Django 3.2.1 on 2021-06-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0037_agenthistory'),
        ('agents', '0037_auto_20210627_0014'),
    ]

    operations = [
    ]
