# Generated by Django 3.2.12 on 2022-03-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0044_auto_20220227_0717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecoveryAction',
        ),
    ]
