# Generated by Django 3.2.12 on 2022-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0045_delete_recoveryaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenthistory',
            name='command',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
