# Generated by Django 4.0.3 on 2022-04-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20211226_0547'),
        ('agents', '0046_alter_agenthistory_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='plat',
            field=models.CharField(default='windows', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='agents', to='clients.site'),
            preserve_default=False,
        ),
    ]
