# Generated by Django 4.0.3 on 2022-04-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0047_alter_agent_plat_alter_agent_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='has_patches_pending',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pending_actions_count',
        ),
    ]
