# Generated by Django 4.0.4 on 2022-04-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0049_agent_agents_agen_monitor_df8816_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='plat_release',
        ),
    ]
