# Generated by Django 4.0.4 on 2022-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0050_remove_agent_plat_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='plat',
            field=models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('darwin', 'macOS')], default='windows', max_length=255),
        ),
    ]
