# Generated by Django 4.0.4 on 2022-05-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0052_alter_agent_monitoring_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenthistory',
            name='status',
        ),
    ]
