# Generated by Django 4.2.22 on 2026-02-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0061_alter_agent_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="default_shell",
            field=models.CharField(
                choices=[
                    ("use_global", "Use global default"),
                    ("cmd", "cmd"),
                    ("powershell", "powershell"),
                    ("bash", "bash"),
                    ("custom", "custom"),
                ],
                default="use_global",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="default_shell_custom",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
