# Generated by Django 4.2.22 on 2026-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0061_alter_agent_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="default_shell",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
