# Generated by Django 3.0.6 on 2020-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0002_check_managed_by_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="overriden_by_policy",
            field=models.BooleanField(default=False),
        ),
    ]
