# Generated by Django 3.1 on 2020-08-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0004_check_parent_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="extra_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="check",
            name="outage_history",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
