# Generated by Django 3.1.4 on 2021-01-09 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0010_auto_20200922_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="run_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.PositiveIntegerField(),
                    blank=True,
                    null=True,
                    size=None,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
