# Generated by Django 3.1.4 on 2021-01-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0016_auto_20210123_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='dashboard_alert',
            field=models.BooleanField(default=False),
        ),
    ]
