# Generated by Django 4.2.20 on 2025-04-10 20:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0032_alter_checkhistory_id_alter_checkresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='success_return_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
