# Generated by Django 3.2.6 on 2021-11-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0013_script_syntax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
