# Generated by Django 3.2.9 on 2021-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0014_alter_script_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='script',
            name='script_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='code_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
