# Generated by Django 4.2.18 on 2026-02-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autotasks', '0041_automatedtask_task_supported_platforms_and_more'),
        ('agents', '0060_agenthistory_collector_all_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenframeScriptSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_agents', models.ManyToManyField(blank=True, help_text='Agents this schedule is deployed to.', related_name='openframe_script_schedules', to='agents.agent')),
                ('managed_task', models.OneToOneField(help_text='The AutomatedTask that holds all schedule config and script actions.', on_delete=django.db.models.deletion.CASCADE, related_name='openframe_script_schedule', to='autotasks.automatedtask')),
            ],
            options={
                'verbose_name': 'Openframe Script Schedule',
                'verbose_name_plural': 'Openframe Script Schedules',
            },
        ),
    ]
