# Generated by Django 3.2.9 on 2021-12-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='auth',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
