# Generated by Django 3.2.9 on 2021-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='auth',
            new_name='configuration',
        ),
        migrations.AddField(
            model_name='integration',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
