# Generated by Django 3.2.9 on 2022-01-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20211214_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='client_org_related',
            field=models.BooleanField(default=False),
        ),
    ]
