# Generated by Django 3.0.5 on 2020-05-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
