# Generated by Django 3.1.4 on 2020-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_dark_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_community_scripts",
            field=models.BooleanField(default=True),
        ),
    ]
