# Generated by Django 3.2 on 2021-04-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_client_tree_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_tree_splitter',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
