# Generated by Django 3.2 on 2021-04-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_client_tree_splitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loading_bar_color',
            field=models.CharField(default='red', max_length=255),
        ),
    ]
