# Generated by Django 3.2.1 on 2021-05-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_urlaction'),
        ('accounts', '0015_user_loading_bar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.urlaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_dblclick_action',
            field=models.CharField(choices=[('editagent', 'Edit Agent'), ('takecontrol', 'Take Control'), ('remotebg', 'Remote Background'), ('urlaction', 'URL Action')], default='editagent', max_length=50),
        ),
    ]
