# Generated by Django 3.2.4 on 2021-06-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_clear_search_when_switching'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_installer_user',
            field=models.BooleanField(default=False),
        ),
    ]
