# Generated by Django 4.2.10 on 2024-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_remove_role_can_ping_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_servertasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_run_servercli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_run_servertasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_servertasks',
            field=models.BooleanField(default=False),
        ),
    ]
