# Generated by Django 4.2.13 on 2024-06-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0037_role_can_manage_servertasks_role_can_run_servercli_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="can_manage_servertasks",
            new_name="can_run_server_scripts",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="can_run_servercli",
            new_name="can_use_webterm",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_run_servertasks",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_view_servertasks",
        ),
    ]
