# Generated by Django 4.2.20 on 2025-06-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_role_can_edit_global_keystore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_schedules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_schedules',
            field=models.BooleanField(default=False),
        ),
    ]
