# Generated by Django 4.2.22 on 2026-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_role_can_use_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_use_terminal",
            field=models.BooleanField(default=False),
        ),
    ]
