# Generated by Django 4.2.30 on 2026-07-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_aiprovider_coresettings_ai_module_enabled_and_more'),
        ('accounts', '0042_copy_mesh_permission_to_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ai_allowed_models',
            field=models.ManyToManyField(blank=True, related_name='role_ai_models', to='core.aimodel'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_use_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_use_ai_autoapprove',
            field=models.BooleanField(default=False),
        ),
    ]
