# Generated by Django 4.2.30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0062_agent_default_shell_agent_default_shell_custom"),
        ("accounts", "0042_copy_mesh_permission_to_terminal"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSHPublicKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, blank=True)),
                ("modified_time", models.DateTimeField(auto_now=True, null=True, blank=True)),
                ("created_by", models.CharField(max_length=255, null=True, blank=True)),
                ("modified_by", models.CharField(max_length=255, null=True, blank=True)),
                ("name", models.CharField(max_length=255)),
                ("key_type", models.CharField(max_length=64)),
                ("key_data", models.TextField()),
                ("fingerprint", models.CharField(max_length=128, unique=True)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssh_keys",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SSHSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, blank=True)),
                ("modified_time", models.DateTimeField(auto_now=True, null=True, blank=True)),
                ("created_by", models.CharField(max_length=255, null=True, blank=True)),
                ("modified_by", models.CharField(max_length=255, null=True, blank=True)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("remote_ip", models.GenericIPAddressField()),
                ("started_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("client_version", models.CharField(blank=True, max_length=255)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssh_sessions",
                        to="agents.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssh_sessions",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
