# Generated by Django 4.2.30 on 2026-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_role_ai_allowed_models_role_can_use_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_use_ai_mutate',
            field=models.BooleanField(default=False),
        ),
    ]
