# Generated by Django 4.2.30 on 2026-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_role_can_use_ai_mutate'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_all_ai_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
