# Generated by Django 4.2.30 on 2026-07-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_role_can_manage_all_ai_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_autoapprove_default',
            field=models.BooleanField(default=False),
        ),
    ]
