# Generated by Django 3.1.1 on 2020-09-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winupdate", "0005_auto_20200905_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="winupdatepolicy",
            name="reprocess_failed_inherit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="winupdatepolicy",
            name="run_time_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily/Weekly"),
                    ("monthly", "Monthly"),
                    ("inherit", "Inherit"),
                ],
                default="inherit",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winupdatepolicy",
            name="reboot_after_install",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("required", "When Required"),
                    ("always", "Always"),
                    ("inherit", "Inherit"),
                ],
                default="inherit",
                max_length=50,
            ),
        ),
    ]
