# Generated by Django 3.1.5 on 2021-01-19 00:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winupdate", "0009_auto_20200922_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="winupdate",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="winupdate",
            name="category_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="winupdate",
            name="kb_article_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="winupdate",
            name="more_info_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="winupdate",
            name="revision_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winupdate",
            name="support_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winupdate",
            name="date_installed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winupdate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winupdate",
            name="guid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="winupdate",
            name="kb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="winupdate",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
