# Generated by Django 3.1.4 on 2021-01-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0013_auto_20210129_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='dashboard_alert',
            field=models.BooleanField(default=False),
        ),
    ]
