# Generated by Django 3.1.7 on 2021-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0017_auto_20210210_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='run_asap_after_missed',
            field=models.BooleanField(default=False),
        ),
    ]
