# Generated by Django 3.1.7 on 2021-04-04 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_globalkvstore'),
        ('scripts', '0007_script_args'),
        ('autotasks', '0018_automatedtask_run_asap_after_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='custom_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autotask', to='core.customfield'),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='retvalue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automatedtask',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoscript', to='scripts.script'),
        ),
    ]
