# Generated by Django 3.1.7 on 2021-04-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0019_auto_20210404_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='sync_status',
            field=models.CharField(choices=[('synced', 'Synced With Agent'), ('notsynced', 'Waiting On Agent Checkin'), ('pendingdeletion', 'Pending Deletion on Agent'), ('initial', 'Initial Task Sync')], default='initial', max_length=100),
        ),
    ]
