# Generated by Django 3.2.9 on 2021-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0023_auto_20210917_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedtask',
            name='run_time_days',
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='actions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='daily_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='monthly_days_of_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='monthly_months_of_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='monthly_weeks_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='random_task_delay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='stop_task_at_duration_end',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='task_instance_policy',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='task_repetition_duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='task_repetition_interval',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='weekly_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automatedtask',
            name='task_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('monthlydow', 'Monthly Day of Week'), ('checkfailure', 'On Check Failure'), ('manual', 'Manual'), ('runonce', 'Run Once')], default='manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='automatedtask',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, default=120),
        ),
    ]
