# Generated by Django 3.2.10 on 2021-12-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0024_auto_20211214_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='continue_on_error',
            field=models.BooleanField(default=True),
        ),
    ]
