# Generated by Django 3.2.10 on 2021-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0025_automatedtask_continue_on_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='monthly_days_of_month',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
