# Generated by Django 3.2.11 on 2022-01-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0027_auto_20220107_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='actions',
            field=models.JSONField(default=list),
        ),
    ]
