# Generated by Django 3.2.10 on 2022-01-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0028_alter_automatedtask_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='task_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('monthlydow', 'Monthly Day of Week'), ('checkfailure', 'On Check Failure'), ('manual', 'Manual'), ('runonce', 'Run Once'), ('scheduled', 'Scheduled')], default='manual', max_length=100),
        ),
    ]
