# Generated by Django 4.0.5 on 2022-06-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0036_alter_automatedtask_win_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='retcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
