# Generated by Django 3.1.2 on 2020-11-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0024_auto_20201101_2319"),
        ("accounts", "0005_auto_20201002_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="agents.agent",
            ),
        ),
    ]
