# Generated by Django 3.1.7 on 2021-02-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_default_agent_tbl_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agents_per_page',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
