# Generated by Django 3.0.8 on 2020-07-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winupdate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winupdatepolicy",
            name="reboot_after_install",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("required", "When Required"),
                    ("always", "Always"),
                ],
                default="never",
                max_length=50,
            ),
        ),
    ]
