# Generated by Django 3.2.12 on 2022-02-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0011_auto_20210917_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winupdate',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='winupdate',
            name='needs_reboot',
        ),
    ]
