[supervisord]
nodaemon=true
logfile=${TACTICAL_DIR}/logs/supervisord.log
pidfile=${TACTICAL_DIR}/supervisor/supervisord.pid

[include]
files = ${TACTICAL_DIR}/supervisor/*.conf

[program:nats-server]
command=nats-server --config ${NATS_CONFIG}
stdout_logfile=${TACTICAL_DIR}/logs/nats-server.log
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:config-watcher]
command=/bin/bash ${TACTICAL_DIR}/supervisor/config-watcher.sh
directory=${TACTICAL_DIR}/api
user=root
autostart=true
autorestart=true
startretries=5
stopwaitsecs=10
stdout_logfile=${TACTICAL_DIR}/logs/agent-listener.log
stdout_logfile_maxbytes=50MB
redirect_stderr=true
environment=PYTHONUNBUFFERED="1",PYTHONPATH="${TACTICAL_DIR}/api",DJANGO_SETTINGS_MODULE="tacticalrmm.settings",REDIS_HOST="${REDIS_HOST}"

[program:nats-api]
command=/bin/bash -c "/usr/local/bin/nats-api -config ${NATS_API_CONFIG}"
stdout_logfile=${TACTICAL_DIR}/logs/nats-api.log
stdout_logfile_maxbytes=0
redirect_stderr=true
