{{- if .Values.tactical.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tactical-backend
spec:
  clusterIP: None
  selector:
    {{- include "tacticalrmm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tactical-backend
  ports:
  - port: {{ .Values.tactical.backend.port }}
    targetPort: {{ .Values.tactical.backend.port }}
    protocol: TCP
{{- end }}
