{{- if .Values.tactical.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tactical-backend
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.tactical.backend.revisionHistoryLimit }}

  serviceName: tactical-backend

  selector:
    matchLabels:
      {{- include "tacticalrmm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tactical-backend
  template:
    metadata:
      labels:
        {{- include "tacticalrmm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tactical-backend

    spec:
      {{- if .Values.tactical.priorityClass.enabled }}
      priorityClassName: tactical-backend
      {{- end }}

      initContainers:
        - name: wait-for-dependencies
          image: "{{ .Values.tactical.initImage.registry }}/{{ .Values.tactical.initImage.repository }}:{{ .Values.tactical.initImage.tag }}"
          envFrom:
            - configMapRef:
                name: tactical-backend
            - configMapRef:
                name: tactical-datasources
          command: ['sh', '-c', '
            echo "PostgreSQL waiting..." && until nc -z $POSTGRES_HOST $POSTGRES_PORT; do sleep 2; done && echo "PostgreSQL ready!" &&
            echo "Redis waiting..." && until nc -z $REDIS_HOST $REDIS_PORT; do sleep 2; done && echo "Redis ready!"
            {{- if (index .Values "tactical-nginx").enabled }} &&
            echo "Nginx waiting..." && until nc -z tactical-nginx.{{ .Release.Namespace }}.svc.cluster.local 80; do sleep 2; done && echo "Nginx ready!"
            {{- end }}
            ']

      containers:
        - name: tactical-backend
          image: "{{ .Values.tactical.image.registry }}/{{ .Values.tactical.image.repository }}:{{ .Values.tactical.image.tag }}"
          args: ["tactical-backend"]
          ports:
            - containerPort: {{ .Values.tactical.backend.port }}
              name: http

          envFrom:
            - configMapRef:
                name: tactical-backend
            - secretRef:
                name: {{ .Values.tactical.existingSecret | default "tactical-backend" }}
            - configMapRef:
                name: tactical-datasources
            - secretRef:
                name: {{ .Values.postgres.external.existingSecret | default "tactical-datasources" }}

          resources:
            {{- toYaml .Values.tactical.backend.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: backend-data
              mountPath: /opt/tactical
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: tactical-backend
{{- end }}
