# Generated by Django 3.2.11 on 2022-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
