# Generated by Django 4.1.2 on 2022-11-16 21:58

from django.db import migrations, models
import ee.reporting.storage
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0002_alter_reporttemplate_template_css"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=ee.reporting.storage.ReportAssetStorage(
                            location="/opt/tactical/reporting/assets"
                        ),
                        upload_to="",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
