# Generated by Django 4.2.6 on 2023-11-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_reporttemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthtmltemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
