# Generated by Django 4.1.2 on 2022-11-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_reportasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDataQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('query', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportHTMLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('html', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='template_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='htmltemplate', to='reporting.reporthtmltemplate'),
        ),
    ]
