# Generated by Django 4.2.22 on 2025-06-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_reportasset_created_by_reportasset_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='email_settings',
            field=models.JSONField(default=dict),
        ),
    ]
