# Generated by Django 4.1.2 on 2022-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_reportdataquery_reporthtmltemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdataquery',
            name='query',
        ),
        migrations.AddField(
            model_name='reportdataquery',
            name='yaml_query',
            field=models.TextField(default='this'),
            preserve_default=False,
        ),
    ]
