# Generated by Django 4.1.2 on 2022-11-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_remove_reportdataquery_query_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttemplate',
            old_name='template_base',
            new_name='template_html',
        ),
    ]
