# Generated by Django 4.2.22 on 2025-06-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0005_reportschedule_email_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportschedule",
            name="no_email",
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="send_report_email",
            field=models.BooleanField(default=True),
        ),
    ]
