# Generated by Django 4.2.22 on 2025-07-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_reportschedule_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
