# Generated by Django 4.1.3 on 2022-12-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_rename_template_base_reporttemplate_template_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdataquery',
            name='yaml_query',
        ),
        migrations.AddField(
            model_name='reportdataquery',
            name='json_query',
            field=models.JSONField(default=dict),
        ),
    ]
