# Generated by Django 4.2.22 on 2025-06-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_remove_reportschedule_no_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportasset",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reportasset",
            name="created_time",
        ),
        migrations.RemoveField(
            model_name="reportasset",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="reportasset",
            name="modified_time",
        ),
    ]
