# Generated by Django 4.2.22 on 2025-07-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_reportschedule_timezone'),
        ('reporting', '0007_remove_reportasset_created_by_and_more'),
    ]

    operations = [
    ]
