# Generated by Django 4.1.8 on 2023-05-09 15:44

from django.db import migrations, models
import ee.reporting.storage


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_reporttemplate_type_alter_reportasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='template_variables',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdataquery',
            name='json_query',
            field=models.JSONField(),
        ),
    ]
