# Generated by Django 4.1.8 on 2023-05-13 03:26

import django.contrib.postgres.fields
from django.db import migrations, models
import ee.reporting.storage


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_reporttemplate_template_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='depends_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='reportasset',
            name='file',
            field=models.FileField(storage=ee.reporting.storage.ReportAssetStorage(base_url='https://api.simplermm.com/reporting/assets/', location='/opt/tactical/reporting/assets'), unique=True, upload_to=''),
        ),
    ]
