# Generated by Django 3.1.4 on 2020-12-10 21:45

from django.db import migrations
from django.conf import settings
import os
import base64
from pathlib import Path


def move_scripts_to_db(apps, schema_editor):
    print("")
    Script = apps.get_model("scripts", "Script")
    for script in Script.objects.all():
        if not script.script_type == "builtin":

            filepath = f"{settings.SCRIPTS_DIR}/userdefined/{script.filename}"

            # test if file exists
            if os.path.exists(filepath):
                print(f"Found script {script.name}. Importing code.")

                with open(filepath, "rb") as f:
                    script_bytes = f.read().decode("utf-8").encode("ascii", "ignore")
                    script.code_base64 = base64.b64encode(script_bytes).decode("ascii")
                    script.save(update_fields=["code_base64"])
            else:
                print(
                    f"Script file {script.name} was not found on the disk. You will need to edit the script in the UI"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0005_auto_20201207_1606"),
    ]

    operations = [migrations.RunPython(move_scripts_to_db, migrations.RunPython.noop)]
