# Generated by Django 3.1.7 on 2021-03-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_auto_20201207_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='default_timeout',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
