# Generated by Django 3.1.7 on 2021-04-01 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_script_default_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='args',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
