# Generated by Django 3.2.12 on 2022-03-11 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0016_auto_20220217_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='supported_platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
    ]
