# Generated by Django 4.1.3 on 2022-11-26 01:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0018_script_run_as_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="env_vars",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
