# Generated by Django 3.2.6 on 2021-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_auto_20210917_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='syntax',
            field=models.TextField(blank=True, null=True),
        ),
    ]
