# Generated by Django 3.2.12 on 2022-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0015_auto_20211128_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='shell',
            field=models.CharField(choices=[('powershell', 'Powershell'), ('cmd', 'Batch (CMD)'), ('python', 'Python'), ('shell', 'Shell')], default='powershell', max_length=100),
        ),
        migrations.AlterField(
            model_name='scriptsnippet',
            name='shell',
            field=models.CharField(choices=[('powershell', 'Powershell'), ('cmd', 'Batch (CMD)'), ('python', 'Python'), ('shell', 'Shell')], default='powershell', max_length=15),
        ),
    ]
