# Generated by Django 4.0.6 on 2022-07-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0017_auto_20220311_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='run_as_user',
            field=models.BooleanField(default=False),
        ),
    ]
