# Generated by Django 4.2.10 on 2024-02-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0019_script_env_vars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="script",
            name="shell",
            field=models.CharField(
                choices=[
                    ("powershell", "Powershell"),
                    ("cmd", "Batch (CMD)"),
                    ("python", "Python"),
                    ("shell", "Shell"),
                    ("nushell", "Nushell"),
                    ("deno", "Deno"),
                ],
                default="powershell",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="scriptsnippet",
            name="shell",
            field=models.CharField(
                choices=[
                    ("powershell", "Powershell"),
                    ("cmd", "Batch (CMD)"),
                    ("python", "Python"),
                    ("shell", "Shell"),
                    ("nushell", "Nushell"),
                    ("deno", "Deno"),
                ],
                default="powershell",
                max_length=15,
            ),
        ),
    ]
