# Generated by Django 3.0.6 on 2020-05-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checks', '0001_initial'),
        ('autotasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoscript', to='checks.Script'),
        ),
    ]
