# Generated by Django 3.0.7 on 2020-07-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automatedtask",
            name="managed_by_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="automatedtask",
            name="parent_task",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
