# Generated by Django 3.0.6 on 2020-05-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_time_zone'),
        ('autotasks', '0002_automatedtask_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autotasks', to='agents.Agent'),
        ),
    ]
