# Generated by Django 3.0.6 on 2020-05-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('autotasks', '0003_auto_20200525_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autotasks', to='automation.Policy'),
        ),
    ]
