# Generated by Django 3.1.4 on 2021-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0010_migrate_days_to_bitdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='alert_severity',
            field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], default='None', max_length=30, null=True),
        ),
    ]
