# Generated by Django 3.1.4 on 2021-02-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0016_automatedtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedtask',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='resolved_email_sent',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='resolved_text_sent',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='text_sent',
        ),
    ]
