# Generated by Django 3.1.7 on 2021-04-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customfield_hide_in_ui'),
        ('autotasks', '0020_auto_20210421_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='custom_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autotasks', to='core.customfield'),
        ),
    ]
