# Generated by Django 3.2.11 on 2022-01-07 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0026_alter_automatedtask_monthly_days_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='daily_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='automatedtask',
            name='weekly_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
