# Generated by Django 3.2.12 on 2022-03-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0029_alter_automatedtask_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedtask',
            name='managed_by_policy',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='script',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='script_args',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='timeout',
        ),
        migrations.CreateModel(
            name='PolicyTaskResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retvalue', models.TextField(blank=True, null=True)),
                ('retcode', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('execution_time', models.CharField(default='0.0000', max_length=100)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('pending', 'Pending')], default='pending', max_length=30)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced With Agent'), ('notsynced', 'Waiting On Agent Checkin'), ('pendingdeletion', 'Pending Deletion on Agent'), ('initial', 'Initial Task Sync')], default='initial', max_length=100)),
                ('policy_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policytaskresults', to='autotasks.automatedtask')),
            ],
        ),
    ]
