# Generated by Django 3.2.12 on 2022-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0030_auto_20220328_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='win_task_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
