# Generated by Django 3.2.12 on 2022-03-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0026_auto_20220325_0142'),
        ('autotasks', '0030_auto_20220325_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='assigned_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedtasks', to='checks.check'),
        ),
    ]
