# Generated by Django 3.2.12 on 2022-04-01 22:49

from django.db import migrations


def migrate_task_results(apps, schema_editor):
    AutomatedTask = apps.get_model("autotasks", "AutomatedTask")
    TaskResult = apps.get_model("autotasks", "TaskResult")
    for task in AutomatedTask.objects.exclude(agent=None):
        TaskResult(
            task=task,
            agent=task.agent,
            retcode=task.retcode,
            stdout=task.stdout,
            stderr=task.stderr,
            execution_time=task.execution_time,
            last_run=task.last_run,
            status=task.status,
            sync_status=task.sync_status,
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("autotasks", "0030_auto_20220401_2244"),
    ]

    operations = [
        migrations.RunPython(migrate_task_results),
    ]
