# Generated by Django 3.2.12 on 2022-03-26 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0046_alter_agenthistory_command'),
        ('autotasks', '0031_alter_automatedtask_assigned_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskresults', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskresults', to='autotasks.automatedtask'),
        ),
    ]
