# Generated by Django 3.2.12 on 2022-04-02 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0033_auto_20220402_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedtask',
            name='script',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='script_args',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='timeout',
        ),
    ]
