# Generated by Django 4.0.3 on 2022-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0035_auto_20220415_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='win_task_name',
            field=models.CharField(blank=True, default='TacticalRMM_vRdxtdnbgoQSEADfuxXuIiegSOSNhMElwgr', max_length=255, unique=True),
        ),
    ]
