# Generated by Django 4.2.7 on 2023-11-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0038_add_missing_env_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='task_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('monthlydow', 'Monthly Day of Week'), ('checkfailure', 'On Check Failure'), ('manual', 'Manual'), ('runonce', 'Run Once'), ('onboarding', 'Onboarding'), ('scheduled', 'Scheduled')], default='manual', max_length=100),
        ),
    ]
