# Generated by Django 4.2.9 on 2024-02-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0039_alter_automatedtask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='server_task',
            field=models.BooleanField(default=False),
        ),
    ]
