# Generated by Django 4.2.9 on 2024-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotasks', '0040_automatedtask_server_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='crontab_schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
