# Generated by Django 4.2.10 on 2024-04-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0059_alter_agenthistory_id'),
        ('autotasks', '0040_alter_taskresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='crontab_schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='server_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskresults', to='agents.agent'),
        ),
    ]
