# Generated by Django 3.1.7 on 2021-03-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20200810_0544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChocoLog',
        ),
    ]
