# Generated by Django 2.2.4 on 2019-09-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_uninstall_inprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(default='n/a', max_length=30),
        ),
    ]
