# Generated by Django 2.2.6 on 2019-10-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20190922_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='system_info',
        ),
    ]
