# Generated by Django 2.2.6 on 2019-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agent_system_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ping_check_interval',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
