# Generated by Django 2.2.7 on 2019-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='antivirus',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
