# Generated by Django 3.1 on 2020-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="subject",
        ),
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Informational"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                max_length=100,
            ),
        ),
    ]