# Generated by Django 3.1.2 on 2020-10-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0010_auto_20200922_1344"),
        ("alerts", "0002_auto_20200815_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="assigned_check",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert",
                to="checks.check",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]