# Generated by Django 3.1.2 on 2020-11-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_auto_20200922_1344"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PolicyExclusions",
        ),
    ]
