# Generated by Django 3.1.7 on 2021-03-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_agent_offline_time'),
        ('clients', '0009_auto_20210212_1408'),
        ('automation', '0007_policy_alert_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='excluded_agents',
            field=models.ManyToManyField(blank=True, related_name='policy_exclusions', to='agents.Agent'),
        ),
        migrations.AddField(
            model_name='policy',
            name='excluded_clients',
            field=models.ManyToManyField(blank=True, related_name='policy_exclusions', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='policy',
            name='excluded_sites',
            field=models.ManyToManyField(blank=True, related_name='policy_exclusions', to='clients.Site'),
        ),
    ]
