# Generated by Django 3.1.4 on 2021-01-23 01:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autotasks', '0010_migrate_days_to_bitdays'),
        ('scripts', '0006_auto_20201210_2145'),
        ('clients', '0008_auto_20201103_1430'),
        ('agents', '0026_auto_20201125_2334'),
        ('automation', '0006_delete_policyexclusions'),
        ('checks', '0016_auto_20210123_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('always_email', models.BooleanField(default=False)),
                ('always_text', models.BooleanField(default=False)),
                ('email_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, null=True, size=None)),
                ('text_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, null=True, size=None)),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_alert_severity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None)),
                ('text_alert_severity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None)),
                ('email_on_resolved', models.BooleanField(default=False)),
                ('text_on_resolved', models.BooleanField(default=False)),
                ('actions', models.ManyToManyField(blank=True, related_name='alert_templates', to='scripts.Script')),
            ],
        ),
        migrations.CreateModel(
            name='AlertExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert', to='alerts.alerttemplate')),
                ('clients', models.ManyToManyField(related_name='alert_exclusions', to='clients.Client')),
                ('policies', models.ManyToManyField(related_name='alert_exclusions', to='automation.Policy')),
                ('sites', models.ManyToManyField(related_name='alert_exclusions', to='clients.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('alert_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agents.agent')),
                ('assigned_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='checks.check')),
                ('assigned_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='autotasks.automatedtask')),
            ],
        ),
    ]
