# Generated by Django 3.1.4 on 2021-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerttemplate',
            old_name='always_email',
            new_name='always_email_on_error',
        ),
        migrations.RenameField(
            model_name='alerttemplate',
            old_name='always_text',
            new_name='always_email_on_warning',
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='always_text_on_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='always_text_on_warning',
            field=models.BooleanField(default=False),
        ),
    ]
