# Generated by Django 3.1.4 on 2021-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='snoozed',
            field=models.BooleanField(default=False),
        ),
    ]
