# Generated by Django 3.1.4 on 2021-01-20 18:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20210120_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerttemplate',
            old_name='always_email_on_error',
            new_name='always_email',
        ),
        migrations.RenameField(
            model_name='alerttemplate',
            old_name='always_email_on_warning',
            new_name='always_text',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='always_text_on_error',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='always_text_on_warning',
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='email_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='text_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
