# Generated by Django 3.1.4 on 2021-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_snoozed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('availability', 'Availability'), ('check', 'Check'), ('task', 'Task'), ('custom', 'Custom')], default='availability', max_length=20),
        ),
    ]
