# Generated by Django 3.1.4 on 2021-01-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_alert_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='resolved_time',
            new_name='resolved_on',
        ),
    ]
