# Generated by Django 3.1.4 on 2021-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_auto_20201210_2145'),
        ('alerts', '0004_auto_20210207_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='resolved_actions',
            field=models.ManyToManyField(blank=True, related_name='alert_templates_resolved', to='scripts.Script'),
        ),
    ]
