# Generated by Django 3.1.4 on 2021-01-28 04:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20210127_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerttemplate',
            old_name='email_alert_severity',
            new_name='check_email_alert_severity',
        ),
        migrations.RenameField(
            model_name='alerttemplate',
            old_name='text_alert_severity',
            new_name='check_text_alert_severity',
        ),
        migrations.RemoveField(
            model_name='alertexclusion',
            name='policies',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='always_email',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='always_text',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='email_on_resolved',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='text_on_resolved',
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_always_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_always_text',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_email_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_include_desktops',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_periodic_alert_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_text_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_always_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_always_text',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_email_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_include_desktops',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_periodic_alert_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_text_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_always_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_always_text',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_email_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_email_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_include_desktops',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_periodic_alert_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_text_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_text_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
