# Generated by Django 3.2.1 on 2021-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20210217_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
