# Generated by Django 3.1.4 on 2021-01-29 22:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20210128_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_alert_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='agent_always_alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_alert_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_always_alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='check_dashboard_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_alert_on_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_always_alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='task_dashboard_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
