# Generated by Django 3.1.4 on 2021-01-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20210129_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerttemplate',
            name='check_include_desktops',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='task_include_desktops',
        ),
    ]
