# Generated by Django 3.1.4 on 2021-01-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_auto_20201210_2145'),
        ('alerts', '0009_auto_20210129_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='alert_templates', to='scripts.Script'),
        ),
    ]
