# Generated by Django 4.0.3 on 2022-04-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0047_alter_agent_plat_alter_agent_site'),
        ('alerts', '0010_auto_20210917_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agents.agent'),
            preserve_default=False,
        ),
    ]
