# Generated by Django 3.1.4 on 2021-01-30 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alerttemplate_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttemplate',
            name='check_dashboard_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='check_email_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='task_dashboard_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='task_email_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='task_text_alert_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=25), blank=True, default=list, size=None),
        ),
    ]
