# Generated by Django 4.0.3 on 2022-04-09 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0047_alter_agent_plat_alter_agent_site'),
        ('alerts', '0011_alter_alert_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agents.agent'),
        ),
    ]
