# Generated by Django 4.1.3 on 2022-11-26 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0012_alter_alert_action_retcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerttemplate",
            name="action_env_vars",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="alerttemplate",
            name="resolved_action_env_vars",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
