# Generated by Django 3.1.4 on 2021-02-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_agent_overdue_dashboard_alert'),
        ('clients', '0009_auto_20210123_0149'),
        ('alerts', '0012_auto_20210130_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='excluded_agents',
            field=models.ManyToManyField(related_name='alert_exclusions', to='agents.Agent'),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='excluded_clients',
            field=models.ManyToManyField(related_name='alert_exclusions', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='excluded_sites',
            field=models.ManyToManyField(related_name='alert_exclusions', to='clients.Site'),
        ),
        migrations.DeleteModel(
            name='AlertExclusion',
        ),
    ]
