# Generated by Django 3.1.4 on 2021-02-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_auto_20210202_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerttemplate',
            name='agent_alert_on_resolved',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='check_alert_on_resolved',
        ),
        migrations.RemoveField(
            model_name='alerttemplate',
            name='task_alert_on_resolved',
        ),
    ]
