# Generated by Django 3.1.4 on 2021-02-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_auto_20210206_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentOutage',
        ),
    ]
