# Generated by Django 3.1.6 on 2021-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0029_delete_agentoutage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='offline_time',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
