# Generated by Django 3.0.2 on 2020-01-10 00:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChocoSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chocos', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
