# Generated by Django 3.0.2 on 2020-02-02 04:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_agent_choco_installed'),
        ('software', '0002_chocolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolog',
            name='installed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', django.contrib.postgres.fields.jsonb.JSONField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agent')),
            ],
        ),
    ]
