# Generated by Django 3.0.7 on 2020-06-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0003_check_overriden_by_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="parent_check",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
