# Generated by Django 3.1.4 on 2021-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0011_checkhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkhistory",
            name="y",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
