# Generated by Django 3.1.4 on 2021-01-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0013_auto_20210110_0505"),
        ("checks", "0011_check_run_history"),
    ]

    operations = []
