# Generated by Django 3.1.4 on 2021-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0018_auto_20210205_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='resolved_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='resolved_text_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
