# Generated by Django 3.1.7 on 2021-03-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0022_check_number_of_events_b4_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='run_interval',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
