# Generated by Django 4.0.3 on 2022-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0028_auto_20220401_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='alert_severity',
            field=models.CharField(blank=True, choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], max_length=15, null=True),
        ),
    ]
