# Generated by Django 3.1.4 on 2021-02-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20210212_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='action_timeout',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_action_timeout',
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='action_timeout',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='resolved_action_timeout',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
