# Generated by Django 3.2.1 on 2021-07-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20210721_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttemplate',
            name='agent_script_actions',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='check_script_actions',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='task_script_actions',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
