# Generated by Django 3.1.4 on 2021-01-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_show_community_scripts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_dblclick_action",
            field=models.CharField(
                choices=[
                    ("editagent", "Edit Agent"),
                    ("takecontrol", "Take Control"),
                    ("remotebg", "Remote Background"),
                ],
                default="editagent",
                max_length=50,
            ),
        ),
    ]
