# Generated by Django 3.2.1 on 2021-05-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210508_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('can_use_mesh', models.BooleanField(default=False)),
                ('can_uninstall_agents', models.BooleanField(default=False)),
                ('can_update_agents', models.BooleanField(default=False)),
                ('can_edit_agent', models.BooleanField(default=False)),
                ('can_manage_procs', models.BooleanField(default=False)),
                ('can_view_eventlogs', models.BooleanField(default=False)),
                ('can_send_cmd', models.BooleanField(default=False)),
                ('can_reboot_agents', models.BooleanField(default=False)),
                ('can_install_agents', models.BooleanField(default=False)),
                ('can_run_scripts', models.BooleanField(default=False)),
                ('can_run_bulk', models.BooleanField(default=False)),
                ('can_manage_notes', models.BooleanField(default=False)),
                ('can_edit_core_settings', models.BooleanField(default=False)),
                ('can_do_server_maint', models.BooleanField(default=False)),
                ('can_code_sign', models.BooleanField(default=False)),
                ('can_manage_checks', models.BooleanField(default=False)),
                ('can_run_checks', models.BooleanField(default=False)),
                ('can_manage_clients', models.BooleanField(default=False)),
                ('can_manage_sites', models.BooleanField(default=False)),
                ('can_manage_deployments', models.BooleanField(default=False)),
                ('can_manage_automation_policies', models.BooleanField(default=False)),
                ('can_manage_autotasks', models.BooleanField(default=False)),
                ('can_run_autotasks', models.BooleanField(default=False)),
                ('can_view_auditlogs', models.BooleanField(default=False)),
                ('can_manage_pendingactions', models.BooleanField(default=False)),
                ('can_view_debuglogs', models.BooleanField(default=False)),
                ('can_manage_scripts', models.BooleanField(default=False)),
                ('can_manage_alerts', models.BooleanField(default=False)),
                ('can_manage_winsvcs', models.BooleanField(default=False)),
                ('can_manage_software', models.BooleanField(default=False)),
                ('can_manage_winupdates', models.BooleanField(default=False)),
                ('can_manage_accounts', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_code_sign',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_do_server_maint',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_core_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_install_agents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_accounts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_alerts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_automation_policies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_autotasks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_checks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_clients',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_deployments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_pendingactions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_procs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_scripts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_sites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_software',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_winsvcs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_winupdates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_reboot_agents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_run_autotasks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_run_bulk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_run_checks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_run_scripts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_send_cmd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_uninstall_agents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_update_agents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_use_mesh',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_view_auditlogs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_view_debuglogs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_view_eventlogs',
        ),
    ]
