# Generated by Django 3.2.4 on 2021-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_role_can_view_core_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clear_search_when_switching',
            field=models.BooleanField(default=True),
        ),
    ]
