# Generated by Django 3.2.6 on 2021-11-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20211022_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_customfields',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_customfields',
            field=models.BooleanField(default=False),
        ),
    ]
