# Generated by Django 4.2.1 on 2023-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0032_alter_user_default_agent_tbl_tab"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dash_info_color",
            field=models.CharField(default="info", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="dash_negative_color",
            field=models.CharField(default="negative", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="dash_positive_color",
            field=models.CharField(default="positive", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="dash_warning_color",
            field=models.CharField(default="warning", max_length=255),
        ),
    ]
