# Generated by Django 4.2.5 on 2023-10-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_role_can_send_wol"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_manage_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="can_view_reports",
            field=models.BooleanField(default=False),
        ),
    ]
