# Generated by Django 4.2.7 on 2023-11-09 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_role_can_manage_reports_role_can_view_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="can_ping_agents",
        ),
    ]
