# Generated by Django 4.2.16 on 2024-10-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_role_can_run_server_scripts_role_can_use_webterm"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_edit_global_keystore",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="can_view_global_keystore",
            field=models.BooleanField(default=False),
        ),
    ]
