# Generated by Django 3.0.6 on 2020-05-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
