# Generated by Django 3.1.7 on 2021-03-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientcustomfield_sitecustomfield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('client', 'name')},
        ),
    ]
