# Generated by Django 3.1.7 on 2021-03-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20210321_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
