# Generated by Django 3.2.6 on 2021-10-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20211010_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='client',
        ),
    ]
