# Generated by Django 4.0.3 on 2022-04-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20211226_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='agent_count',
        ),
        migrations.RemoveField(
            model_name='site',
            name='agent_count',
        ),
    ]
