{{- if .Values.tactical.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tactical-celerybeat
spec:
  selector:
    {{- include "tacticalrmm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tactical-celerybeat
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
{{- end }}
