# Generated by Django 3.1.7 on 2021-03-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
