# Generated by Django 3.1.7 on 2021-03-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210318_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('model', 'name')},
        ),
    ]
