# Generated by Django 3.1.7 on 2021-03-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210329_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='checkbox_value',
            new_name='default_value_bool',
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='default_value',
            new_name='default_value_string',
        ),
    ]
