# Generated by Django 3.1.7 on 2021-04-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20210415_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='hide_in_ui',
            field=models.BooleanField(default=False),
        ),
    ]
