# Generated by Django 3.2.1 on 2021-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210707_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='agent_debug_level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='debug_log_prune_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='agent_history_prune_days',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
