# Generated by Django 4.0.3 on 2022-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_coresettings_email_alert_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='mesh_disable_auto_login',
            field=models.BooleanField(default=False),
        ),
    ]
