# Generated by Django 4.2 on 2023-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_coresettings_default_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='open_ai_model',
            field=models.CharField(blank=True, default='gpt-3.5-turbo', max_length=255),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='open_ai_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
