# Generated by Django 4.2.10 on 2024-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_coresettings_mesh_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="sync_mesh_with_trmm",
            field=models.BooleanField(default=True),
        ),
    ]
