# Generated by Django 4.2.16 on 2024-11-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_coresettings_notify_on_warning_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="block_local_user_logon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="sso_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
