# Generated by Django 4.2.27 on 2026-06-10 19:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0024_alter_deployment_goarch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('https', 'HTTPS'), ('http', 'HTTP'), ('ssh', 'SSH'), ('telnet', 'Telnet')], default='https', max_length=10)),
                ('ip_address', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=443)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('preferred_agents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to='clients.site')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
