# Generated by Django 3.0.7 on 2020-06-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_auto_20200604_1713"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="agents",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="sites",
        ),
        migrations.RemoveField(
            model_name="policyexclusions",
            name="clients",
        ),
    ]
