# Generated by Django 3.0.5 on 2020-04-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automatedtask_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autotaskpolicy', to='automation.Policy'),
        ),
    ]
