# Generated by Django 3.0.5 on 2020-04-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_auto_20200414_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedtask',
            name='run_manually',
        ),
        migrations.RemoveField(
            model_name='automatedtask',
            name='run_on_check_failure',
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='task_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('checkfailure', 'On Check Failure'), ('manual', 'Manual')], default='manual', max_length=100),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='timeout',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
