# Generated by Django 3.0.5 on 2020-04-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_auto_20200415_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='win_task_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
