# Generated by Django 3.1.4 on 2021-01-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20210120_2252'),
        ('automation', '0006_delete_policyexclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='alert_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_template', to='alerts.alerttemplate'),
        ),
    ]
