# Generated by Django 3.0.5 on 2020-04-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_automatedtask_win_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='execution_time',
            field=models.CharField(default='0.0000', max_length=100),
        ),
    ]
