# Generated by Django 3.1.4 on 2021-02-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_auto_20210202_0312'),
        ('automation', '0007_policy_alert_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='alert_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='alerts.alerttemplate'),
        ),
    ]
