{{- if .Values.tactical.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-celery
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.tactical.celery.revisionHistoryLimit }}

  selector:
    matchLabels:
      {{- include "tacticalrmm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tactical-celery
  template:
    metadata:
      labels:
        {{- include "tacticalrmm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tactical-celery

    spec:
      initContainers:
        - name: wait-for-dependencies
          image: "{{ .Values.tactical.initImage.registry }}/{{ .Values.tactical.initImage.repository }}:{{ .Values.tactical.initImage.tag }}"
          envFrom:
            - configMapRef:
                name: tactical-backend
            - configMapRef:
                name: tactical-datasources
          command: ['sh', '-c', '
            echo "PostgreSQL waiting..." && until nc -z $POSTGRES_HOST $POSTGRES_PORT; do sleep 2; done && echo "PostgreSQL ready!" &&
            echo "Redis waiting..." && until nc -z $REDIS_HOST $REDIS_PORT; do sleep 2; done && echo "Redis ready!" &&
            echo "Backend waiting..." && until nc -z tactical-backend-0.tactical-backend.{{ .Release.Namespace }}.svc.cluster.local 8000; do sleep 2; done && echo "Backend ready!"
            ']

      containers:
        - name: tactical-base
          image: "{{ .Values.tactical.image.registry }}/{{ .Values.tactical.image.repository }}:{{ .Values.tactical.image.tag }}"
          args: ["tactical-celery"]

          envFrom:
            - configMapRef:
                name: tactical-backend
            - secretRef:
                name: {{ .Values.tactical.existingSecret | default "tactical-backend" }}
            - configMapRef:
                name: tactical-datasources
            - secretRef:
                name: {{ .Values.postgres.external.existingSecret | default "tactical-datasources" }}

          resources:
            {{- toYaml .Values.tactical.celery.resources | nindent 12 }}

          livenessProbe:
            exec:
              command: ["cat", "/opt/tactical/tmp/tactical.ready"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["cat", "/opt/tactical/tmp/tactical.ready"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: celery-data
              mountPath: /opt/tactical

      volumes:
        - name: celery-data
          emptyDir: {}
{{- end }}
