# Generated by Django 2.2.3 on 2019-07-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_standardcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardcheck',
            name='disk',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='disk_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='mem_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='ping_failure_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='ping_failures',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='ping_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='ping_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
