# Generated by Django 2.2.6 on 2019-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0008_auto_20191013_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingcheck',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pingcheck',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pingcheck',
            name='status',
            field=models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
