# Generated by Django 2.2.6 on 2019-10-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0013_cpuloadcheck_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='memcheck',
            name='last_run',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memcheck',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memcheck',
            name='status',
            field=models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
