# Generated by Django 2.2.6 on 2019-10-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20190922_1919'),
        ('checks', '0016_memcheck_check_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinServiceCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check'), ('winsvc', 'Win Service Check')], default='winsvc', max_length=30)),
                ('svc_name', models.CharField(max_length=255)),
                ('svc_display_name', models.CharField(max_length=255)),
                ('pass_if_start_pending', models.BooleanField(default=False)),
                ('restart_if_stopped', models.BooleanField(default=False)),
                ('failures', models.PositiveIntegerField(default=1)),
                ('failure_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('pending', 'Pending')], default='pending', max_length=30)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('email_alert', models.BooleanField(default=False)),
                ('text_alert', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winservicechecks', to='agents.Agent')),
            ],
        ),
        migrations.AlterField(
            model_name='cpuloadcheck',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check'), ('winsvc', 'Win Service Check')], default='cpuload', max_length=30),
        ),
        migrations.AlterField(
            model_name='diskcheck',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check'), ('winsvc', 'Win Service Check')], default='diskspace', max_length=30),
        ),
        migrations.AlterField(
            model_name='memcheck',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check'), ('winsvc', 'Win Service Check')], default='memory', max_length=30),
        ),
        migrations.AlterField(
            model_name='pingcheck',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check'), ('winsvc', 'Win Service Check')], default='ping', max_length=30),
        ),
        migrations.AlterField(
            model_name='standardcheck',
            name='check_type',
            field=models.CharField(choices=[('diskspace', 'Disk Space Check'), ('ping', 'Ping Check'), ('cpuload', 'CPU Load Check'), ('memory', 'Memory Check'), ('winsvc', 'Win Service Check')], max_length=30),
        ),
        migrations.CreateModel(
            name='WinServiceCheckEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.WinServiceCheck')),
            ],
        ),
    ]
