# Generated by Django 2.2.6 on 2019-10-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0017_auto_20191013_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardCheck',
        ),
    ]
