# Generated by Django 3.0.4 on 2020-03-30 05:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winupdatepolicy',
            name='run_time_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, null=True, size=None),
        ),
    ]
