# Generated by Django 3.0.4 on 2020-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winupdatepolicy',
            name='run_time_hour',
            field=models.IntegerField(choices=[(0, '12 AM'), (1, '01 AM'), (2, '02 AM'), (3, '03 AM'), (4, '04 AM'), (5, '05 AM'), (6, '06 AM'), (7, '07 AM'), (8, '08 AM'), (9, '09 AM'), (10, '10 AM'), (11, '11 AM'), (12, '12 PM'), (13, '01 PM'), (14, '02 PM'), (15, '03 PM'), (16, '04 PM'), (17, '05 PM'), (18, '06 PM'), (19, '07 PM'), (20, '08 PM'), (21, '09 PM'), (22, '10 PM'), (23, '11 PM')], default=3),
        ),
    ]
