# Generated by Django 3.1 on 2020-08-28 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_auto_20200617_0332"),
        ("agents", "0012_auto_20200810_0544"),
        ("winupdate", "0002_auto_20200715_0445"),
    ]

    operations = [
        migrations.AddField(
            model_name="winupdatepolicy",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winupdatepolicy",
                to="automation.policy",
            ),
        ),
        migrations.AlterField(
            model_name="winupdatepolicy",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winupdatepolicy",
                to="agents.agent",
            ),
        ),
    ]
