# Generated by Django 2.2.7 on 2019-12-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0002_auto_20191201_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winupdate',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winupdates', to='agents.Agent'),
        ),
    ]
