# Generated by Django 3.0 on 2019-12-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0007_winupdate_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winupdate',
            name='result',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
