# Generated by Django 3.0 on 2019-12-09 00:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agent_needs_reboot'),
        ('winupdate', '0008_auto_20191208_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinUpdatePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical', models.CharField(choices=[('manual', 'Manual'), ('approve', 'Approve'), ('ignore', 'Ignore')], default='manual', max_length=100)),
                ('important', models.CharField(choices=[('manual', 'Manual'), ('approve', 'Approve'), ('ignore', 'Ignore')], default='manual', max_length=100)),
                ('moderate', models.CharField(choices=[('manual', 'Manual'), ('approve', 'Approve'), ('ignore', 'Ignore')], default='manual', max_length=100)),
                ('low', models.CharField(choices=[('manual', 'Manual'), ('approve', 'Approve'), ('ignore', 'Ignore')], default='manual', max_length=100)),
                ('other', models.CharField(choices=[('manual', 'Manual'), ('approve', 'Approve'), ('ignore', 'Ignore')], default='manual', max_length=100)),
                ('run_time_hour', models.IntegerField(choices=[(0, '12 AM'), (1, ' 1 AM'), (2, ' 2 AM'), (3, ' 3 AM'), (4, ' 4 AM'), (5, ' 5 AM'), (6, ' 6 AM'), (7, ' 7 AM'), (8, ' 8 AM'), (9, ' 9 AM'), (10, '10 AM'), (11, '11 AM'), (12, '12 PM'), (13, ' 1 PM'), (14, ' 2 PM'), (15, ' 3 PM'), (16, ' 4 PM'), (17, ' 5 PM'), (18, ' 6 PM'), (19, ' 7 PM'), (20, ' 8 PM'), (21, ' 9 PM'), (22, '10 PM'), (23, '11 PM')], default=3)),
                ('run_time_day', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=5), size=None), size=None)),
                ('reboot_after_install', models.CharField(choices=[('never', 'Never'), ('required', 'When Required'), ('always', 'Always')], default='required', max_length=50)),
                ('reprocess_failed', models.BooleanField(default=False)),
                ('reprocess_failed_times', models.PositiveIntegerField(blank=True, null=True)),
                ('email_if_fail', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winupdatepolicy', to='agents.Agent')),
            ],
        ),
    ]
