# Generated by Django 3.0 on 2019-12-09 00:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0009_winupdatepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winupdatepolicy',
            name='run_time_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, null=True, size=None),
        ),
    ]
